### PR TITLE
[ARCTIC-1539][AMS] Make the `updateConfigInternal` method always execute

### LINKED ISSUE #1539: [Bug]: Table refresh not get newly config
### What happened?

A table with optimization disabled via `'self-optimizing.enabled'='false'` did not trigger the optimizer after resetting `'self-optimizing.enabled'='true'`

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. Start AMS
2. Via `ALTER TABLE` set `'self-optimizing.enabled'='false'`
3. Set `'self-optimizing.enabled'='true'` after the table have a new snapshot

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by zhongqishang**
## Why are the changes needed?
Fix #1539 

## Brief change log

  - *Make the `updateConfigInternal` method always execute*
  - *Optimize `updateConfigInternal` logic*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java [hunk 1]
```diff
@@ -180,12 +180,12 @@ public void setPendingInput(OptimizingEvaluator.PendingInput pendingInput) {
...
-      TableConfiguration configuration = tableConfiguration;
-      if (refreshSnapshots(table) || updateConfigInternal(table.properties())) {
+      boolean configChanged = updateConfigInternal(table.properties());
+      if (refreshSnapshots(table) || configChanged) {
         persistUpdatingRuntime();
       }
-      if (configuration != tableConfiguration) {
-        tableHandler.handleTableChanged(this, configuration);
+      if (configChanged) {
+        tableHandler.handleTableChanged(this, tableConfiguration);
```
Comment (wangtaohz) [inline ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java:188]: I think we should use the configuration before changed, because the interface is 
```
public interface TableRuntimeHandler {
  ...
  void handleTableChanged(TableRuntime tableRuntime, OptimizingStatus originalStatus);

  void handleTableChanged(TableRuntime tableRuntime, TableConfiguration originalConfig);
 ...
}

```

And the `originalConfig` means configuration before changed.

Comment (zhongqishang) [reply ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java]: You are right.

**Review by wangtaohz — APPROVED** [review]
LGTM. 

This problem only occurs when `refreshSnapshots(table)` always return true, which means the table keeps writing data every minute.

**Review by shidayang — APPROVED** [review]

**Comment by shidayang** [comment]
LGTM
