### PR TITLE
[ARCTIC-1729] IcebergPartitionPlan impl buildTaskSplitter by Bin-Packing

### LINKED ISSUE #1729: [Bug]: Optimizing task split has not been implemented
### What happened?

 Optimizing task split has not been implemented, so for the iceberg format, there will only one task per partition when doing optimizing.

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
## Why are the changes needed?

fix #1729 
IcebergPartitionPlan should implement buildTaskSplitter

## Brief change log

1. move MixedHivePartitionPlan Bin-Packing to AbstractPartitionPlan
2. IcebergPartitionPlan use Bin-Packing 

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

*before*:
image
*now*
image

## Documentation

  - Does this pull request introduces a new feature? ( no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java [hunk 1]
```diff
@@ -302,4 +304,67 @@ public TaskDescriptor buildTask(OptimizingInputProperties properties) {
...
+      Long sum = allDataFiles.stream().map(f -> f.getFile().fileSizeInBytes()).reduce(0L, Long::sum);
+      int taskCnt = (int) (sum / taskSize) + 1;
+      List<List<FileTask>> packed = new BinPacking.ListPacker<FileTask>(taskSize, taskCnt, true)
+          .pack(allDataFiles, f -> f.getFile().fileSizeInBytes());
+
+      // collect
+      List<SplitTask> results = Lists.newArrayList();
+      for (List<FileTask> fileTasks : packed) {
+        Map<IcebergDataFile, List<IcebergContentFile<?>>> fragmentFiles = com.google.common.collect.Maps.newHashMap();
+        Map<IcebergDataFile, List<IcebergContentFile<?>>> segmentFiles = com.google.common.collect.Maps.newHashMap();
```
Comment (wangtaohz) [inline ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java:360]: We can use `org.apache.iceberg.relocated.com.google.common.collect.Maps` instead of `com.google.common.collect.Maps`.

**Comment by shidayang** [comment]
Thanks for your contribution. BTW, You can associate the original issue using the syntax "fix: #1729 ".

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java [hunk 2]
```diff
@@ -302,4 +304,67 @@ public TaskDescriptor buildTask(OptimizingInputProperties properties) {
...
+
+    public boolean isSegment() {
+      return !isFragment;
+    }
+  }
+
+  protected class BinPackingTaskSplitter implements TaskSplitter {
+
+    @Override
+    public List<SplitTask> splitTasks(int targetTaskCount) {
```
Comment (shidayang) [inline ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java:342]: I think we should use the "targetTaskCount" parameter to control how to split. If we split according to "targetFileSize", the merged file size will definitely be smaller than or equal to "targetFileSize", which is not what we expected.

**Comment by huyuanfeng2018** [comment]
> Thanks for your contribution. BTW, You can associate the original issue using the syntax "fix: #1729 ".

sry, I forgot

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java (hunk 2 above)
Comment (huyuanfeng2018) [reply ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java:342]: @wangtaohz  Can you reply to this question?

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java (hunk 1 above)
Comment (huyuanfeng2018) [reply ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java:360]: I will fix

**Comment by wangtaohz** [comment]
> *before*:
> image
>*now*
> image

After the code modification, the average file size after optimizing seems to have decreased . I'm concerned that the tasks may have been split too small. Could you provide the value of this table property `self-optimizing.target-size`(which decides the split task size)? @huyuanfeng2018

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java (hunk 2 above)
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java:342]: Using `targetFileSize` to split tasks has this flaw, which is an old issue inherited from 0.4.1 (PR #821). I believe that making the split task size `n` times larger than `targetFileSize` can solve this problem.

As for `targetTaskCount`, currently this parameter cannot guarantee that tasks are split into reasonable sizes, more work needs to be done in the generation of `targetTaskCount` to ensure that it is used reasonably for splitting.

**Comment by huyuanfeng2018** [comment]
> > _before_:
> > image
> > _now_
> > image
> 
> After the code modification, the average file size after optimizing seems to have decreased . I'm concerned that the tasks may have been split too small. Could you provide the value of this table property `self-optimizing.target-size`(which decides the split task size)? @huyuanfeng2018

128mb

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java (hunk 1 above)
Comment (huyuanfeng2018) [reply ams/server/src/main/java/com/netease/arctic/server/optimizing/plan/AbstractPartitionPlan.java]: solved

**Review by zhoujinsong — APPROVED** [review]
LGTM and thanks a lot for your contribution!

**Review by wangtaohz — APPROVED** [review]
