### PR TITLE
[ARCTIC-1134][Core] Fix kerberos authenticate failure

### LINKED ISSUE #1134: [Bug]: Kerberos authenticate will fail after a period of time
### What happened?

AMS and Optimizer will kerberos authenticate fail after a period of time,
and the task did not fail or restart.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

_No response_

### Relevant log output

```shell
2023-02-21 19:50:24,210 WARN  com.netease.arctic.optimizer.flink.FlinkConsumer             [] - failed to poll task, retry 0
org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:99) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:418) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:513) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$SwitchingOnClose.collect(StreamSourceContexts.java:103) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at com.netease.arctic.optimizer.flink.FlinkConsumer.run(FlinkConsumer.java:55) [arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) [flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323) [flink-dist_2.12-1.14.6.jar:1.14.6]
Caused by: java.lang.IllegalStateException: failed when load catalog hive_prod
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:151) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.loadCatalog(CatalogLoader.java:177) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:69) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:79) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.buildTable(BaseTaskExecutor.java:87) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.execute(BaseTaskExecutor.java:117) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:74) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:40) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	... 11 more
Caused by: java.lang.RuntimeException: Re-login from keytab failed
	at com.netease.arctic.table.TableMetaStore.getUGI(TableMetaStore.java:293) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:343) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.BasicIcebergCatalog.initialize(BasicIcebergCatalog.java:75) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:146) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.loadCatalog(CatalogLoader.java:177) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:69) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:79) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.buildTable(BaseTaskExecutor.java:87) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.execute(BaseTaskExecutor.java:117) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:74) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:40) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	... 11 more
Caused by: org.apache.hadoop.security.KerberosAuthException: Login failure for principal: /data/yarn/nm/usercache/hive/appcache/application_1667984545171_3215770/container_e38_1667984545171_3215770_01_000010/arctic_krb_conf/bb5c4f4f59f6ef3f166b556d40d4339c_300688@hd-059.com/krb.keytab from keytab /data/yarn/nm/usercache/hive/appcache/application_1667984545171_3215770/container_e38_1667984545171_3215770_01_000010/krb5.keytab javax.security.auth.login.LoginException: java.lang.IllegalArgumentException: Empty nameString not allowed
	at sun.security.krb5.PrincipalName.validateNameStrings(PrincipalName.java:174)
	at sun.security.krb5.PrincipalName.<init>(PrincipalName.java:397)
	at sun.security.krb5.PrincipalName.<init>(PrincipalName.java:468)
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:650)
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.apache.hadoop.security.UserGroupInformation.reloginFromKeytab(UserGroupInformation.java:1261)
	at org.apache.hadoop.security.UserGroupInformation.checkTGTAndReloginFromKeytab(UserGroupInformation.java:1168)
	at com.netease.arctic.table.TableMetaStore.getUGI(TableMetaStore.java:285)
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:343)
	at com.netease.arctic.catalog.BasicIcebergCatalog.initialize(BasicIcebergCatalog.java:75)
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:146)
	at com.netease.arctic.catalog.CatalogLoader.loadCatalog(CatalogLoader.java:177)
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:69)
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:79)
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.buildTable(BaseTaskExecutor.java:87)
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.execute(BaseTaskExecutor.java:117)
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:74)
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:40)
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:418)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:513)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$SwitchingOnClose.collect(StreamSourceContexts.java:103)
	at com.netease.arctic.optimizer.flink.FlinkConsumer.run(FlinkConsumer.java:55)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323)

	at org.apache.hadoop.security.UserGroupInformation.reloginFromKeytab(UserGroupInformation.java:1270) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at org.apache.hadoop.security.UserGroupInformation.checkTGTAndReloginFromKeytab(UserGroupInformation.java:1168) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.table.TableMetaStore.getUGI(TableMetaStore.java:285) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:343) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.BasicIcebergCatalog.initialize(BasicIcebergCatalog.java:75) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:146) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.loadCatalog(CatalogLoader.java:177) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:69) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:79) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.buildTable(BaseTaskExecutor.java:87) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.execute(BaseTaskExecutor.java:117) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:74) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:40) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	... 11 more
Caused by: javax.security.auth.login.LoginException: java.lang.IllegalArgumentException: Empty nameString not allowed
	at sun.security.krb5.PrincipalName.validateNameStrings(PrincipalName.java:174)
	at sun.security.krb5.PrincipalName.<init>(PrincipalName.java:397)
	at sun.security.krb5.PrincipalName.<init>(PrincipalName.java:468)
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:650)
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.apache.hadoop.security.UserGroupInformation.reloginFromKeytab(UserGroupInformation.java:1261)
	at org.apache.hadoop.security.UserGroupInformation.checkTGTAndReloginFromKeytab(UserGroupInformation.java:1168)
	at com.netease.arctic.table.TableMetaStore.getUGI(TableMetaStore.java:285)
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:343)
	at com.netease.arctic.catalog.BasicIcebergCatalog.initialize(BasicIcebergCatalog.java:75)
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:146)
	at com.netease.arctic.catalog.CatalogLoader.loadCatalog(CatalogLoader.java:177)
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:69)
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:79)
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.buildTable(BaseTaskExecutor.java:87)
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.execute(BaseTaskExecutor.java:117)
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:74)
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:40)
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:57)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:56)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:29)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:418)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:513)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$SwitchingOnClose.collect(StreamSourceContexts.java:103)
	at com.netease.arctic.optimizer.flink.FlinkConsumer.run(FlinkConsumer.java:55)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323)

	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:856) ~[?:1.8.0_141]
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) ~[?:1.8.0_141]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) ~[?:1.8.0_141]
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) ~[?:1.8.0_141]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_141]
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) ~[?:1.8.0_141]
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587) ~[?:1.8.0_141]
	at org.apache.hadoop.security.UserGroupInformation.reloginFromKeytab(UserGroupInformation.java:1261) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at org.apache.hadoop.security.UserGroupInformation.checkTGTAndReloginFromKeytab(UserGroupInformation.java:1168) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.table.TableMetaStore.getUGI(TableMetaStore.java:285) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:343) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.BasicIcebergCatalog.initialize(BasicIcebergCatalog.java:75) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:146) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.loadCatalog(CatalogLoader.java:177) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:69) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.catalog.CatalogLoader.load(CatalogLoader.java:79) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.buildTable(BaseTaskExecutor.java:87) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.operator.BaseTaskExecutor.execute(BaseTaskExecutor.java:117) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:74) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at com.netease.arctic.optimizer.flink.FlinkExecuteFunction.processElement(FlinkExecuteFunction.java:40) ~[arctic-optimizer-0.5.0-SNAPSHOT-jar-with-dependencies-for-relogin-test.jar:?]
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:82) ~[flink-dist_2.12-1.14.6.jar:1.14.6]
	... 11 more
```
```


### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by zhongqishang**
## Why are the changes needed?

resolve #1134 

## Brief change log

Reset `sun.security.krb5.principal` before `ugi.checkTGTAndReloginFromKeytab()`.

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zhongqishang** [comment]
@wangtaohz PTAL.

File: core/src/main/java/com/netease/arctic/table/TableMetaStore.java [hunk 1]
```diff
@@ -280,6 +280,7 @@ public synchronized UserGroupInformation getUGI() {
                   LOG.warn("Fail to reflect UserGroupInformation", e);
                 }
               }
+              System.setProperty("sun.security.krb5.principal", krbPrincipal);
```
Comment (wangtaohz) [inline core/src/main/java/com/netease/arctic/table/TableMetaStore.java:283]: To avoid side effects, I think we should 
- not set system property if it is not an unexpected value
- set the system property back to the old value after relogin

The process may be like:
```
String oldSystemPrincipal = System.getProperty("sun.security.krb5.principal");
boolean systemPrincipalChanged = false;
try {
    ...

    if (oldSystemPrincipal != null && !krbPrincipal.equals(oldSystemPrincipal)) {
        System.setProperty("sun.security.krb5.principal", krbPrincipal);
        systemPrincipalChanged = true;
    }
    ugi.checkTGTAndReloginFromKeytab();
} finally {
    ...

    if (systemPrincipalChanged) {
        System.setProperty("sun.security.krb5.principal", oldSystemPrincipal);
    }
}
```

**Review by wangtaohz — COMMENTED** [review]
@zhoujinsong Thanks for your work! I left some comments.

@zhoujinsong Do you have a time to take a look?

File: core/src/main/java/com/netease/arctic/table/TableMetaStore.java (hunk 1 above)
Comment (zhongqishang) [reply core/src/main/java/com/netease/arctic/table/TableMetaStore.java:283]: I agree with the first, but I have a little concern about the second.

> set the system property back to the old value after relogin

`oldSystemPrincipal == null` cause an exception to occur, although I don't know exactly what caused it.
After relogin reset to `null`, the next relogin will get the same value `null`?

Comment (wangtaohz) [reply core/src/main/java/com/netease/arctic/table/TableMetaStore.java:283]: `multiple catalogs with kerberos` is one of the situations we have to handle. 

Besides,  the old value of `sun.security.krb5.principal` is very likely to be used by another authentication process in this JVM, even though we don't know what they are, they may fail if we change the old value.

Comment (zhongqishang) [reply core/src/main/java/com/netease/arctic/table/TableMetaStore.java:283]: > `multiple catalogs with kerberos` is one of the situations we have to handle.
> 
> Besides, the old value of `sun.security.krb5.principal` is very likely to be used by another authentication process in this JVM, even though we don't know what they are, they may fail if we change the old value.

I get

Comment (zhongqishang) [reply core/src/main/java/com/netease/arctic/table/TableMetaStore.java]: BTW, I delete `oldSystemPrincipal != null` because oldSystemPrincipal is null in my test case.

Comment (wangtaohz) [reply core/src/main/java/com/netease/arctic/table/TableMetaStore.java]: Thanks for your quick reply!

I have reviewed the changes, but I still think we should keep the `oldSystemPrincipal != null`. The reason is in most cases, the `sun.security.krb5.principal` is supposed to be null, and it's not necessary to set our `krbPrincipal` into it for these cases.

Also, to avoid the risk of `NullPointerException`, we'd better code it like this

```
    if (oldSystemPrincipal != null && oldSystemPrincipal.equals(krbPrincipal)) {
        System.setProperty("sun.security.krb5.principal", krbPrincipal);
        systemPrincipalChanged = true;
    }
```

**Review by wangtaohz — APPROVED** [review]
LGTM

**Review by zhoujinsong — APPROVED** [review]
LGTM.
