### PR TITLE
[ARCTIC-871] [ARCTIC-756] Fix pending optimizing after change optimizer group and handle table load error

### LINKED ISSUE #756: [Bug]: Failed to get optimizerGroup tables when fail to open metadata
### What happened?

AMS cannot list tables in Optimizers dashboard when fail to open metadata file:
For instances:
- Permission denied: user=root, access=EXECUTE, inode="/path":yyy:supergroup:drwxrwxrw-
- Table metadata not find(Someone manually moved/deleted it)

AMS Optimizer dashboard should display available tables as possible as it could.

### Affects Versions

master/0.4.x

### What engines are you seeing the problem on?

AMS, Optimizer

### How to reproduce

Manually moved/deleted the metadata and try to list tables in Optimizers dashboard

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #871: [Bug]: The table's optimizing status is `pending` if `optimize group` is changed not by Terminal in AMS dashboard
### What happened?

After we change the table properties `optimize group`, but not by Terminal in AMS dashboard, then we start an optimizer of the new optimizer group, but it can't poll any optimize task from this Table.

### Affects Versions

master/0.4.0/

### What engines are you seeing the problem on?

ams

### How to reproduce

1. create a native iceberg table with an optimizer group without any optimizer.
2. change the iceberg table's optimizer group to a new one, but do not use the AMS dashboard, for example, use the API
```
    Table table = loadTable();
    UpdateProperties updateProperties = table.updateProperties();
    updateProperties.set("self-optimizing.group", "new_group");
    updateProperties.commit();
```
3. keep writing data into this table
4. the table's `optimizing status` changes to `pending`, but can't plan any tasks
5. after restarting AMS, then this table can plan tasks and optimize.

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

fix #871  and fix #756 

## Brief change log

  - check tables in queue periodically (use optimize checker)
  - continue loading other tables if failed to load any table
  - add more logs for optimize plan

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java [hunk 1]
```diff
@@ -146,12 +151,12 @@ public List<TableIdentifier> refreshAndListTables() {
 
     addNewTables(toAddTables);
     clearRemovedTables(toRemoveTables);
+    ArrayList<TableIdentifier> validTables = new ArrayList<>(cachedTables.keySet());
     if (!toAddTables.isEmpty() || !toRemoveTables.isEmpty()) {
-      internalCheckOptimizeChecker(
-          this.optimizeStatusCheckInterval == null ? DEFAULT_CHECK_INTERVAL : this.optimizeStatusCheckInterval);
+      internalCheckOptimizeChecker(validTables);
```
Comment (zhoujinsong) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java:156]: Why should we schedule the check task here?

**Comment by wangtaohz** [comment]
fix #875

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java (hunk 1 above)
Comment (wangtaohz) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java:156]: To add the new tables/clear the removed tables as soon as possible

Comment (wangtaohz) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java:156]: I find `internalCheckOptimizeChecker` will be called twice, I will try to fix it.

Comment (XBaith) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java:156]: That's true, `internalCheckOptimizeChecker` will be called at least twice, if always have new tables are added while refresh tables, it will be called again and again.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java [hunk 2]
```diff
@@ -106,22 +107,26 @@ private void init() {
...
-      checkTasks = new ScheduledTasks<>(ThreadPool.Type.OPTIMIZE_CHECK);
+    try {
+      this.optimizeStatusCheckInterval = checkInterval;
+      if (checkTasks == null) {
+        checkTasks = new ScheduledTasks<>(ThreadPool.Type.OPTIMIZE_CHECK);
+      }
+      List<TableIdentifier> validTables = refreshAndListTables();
+      internalCheckOptimizeChecker(validTables);
+    } catch (Throwable t) {
+      LOG.error("unexpected error when checkOptimizeCheckTasks", t);
```
[the remark this answers is not in the document]
Comment (wangtaohz) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java:118]: Yes, we have released the invalid tables. You can find that in `com.netease.arctic.ams.server.utils.ScheduledTasks`

```
  /**
   * Check running tasks, cancel invalid tasks, add new tasks, change task's interval.
   *
   * @param validKeys             - tasks to keep
   * @param intervalSupplier      - generate interval
   * @param taskFactory           - build task
   * @param mayInterruptIfRunning - interrupt task when cancel
   */
  public synchronized void checkRunningTask(Set<K> validKeys,
                                            Function<K, Long> intervalSupplier,
                                            Function<K, T> taskFactory,
                                            boolean mayInterruptIfRunning) {
    Set<K> removedKeys = removeLegacyTaskFromScheduler(validKeys, false);
    if (!CollectionUtils.isEmpty(removedKeys)) {
      LOG.info("{} cancel {} task(s), {}", name, removedKeys.size(), removedKeys);
    }
```

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java (hunk 1 above)
Comment (wangtaohz) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java]: removed internalCheckOptimizeChecker from refreshAndListTables

**Comment by XBaith** [comment]
image
Still pending, I alert `optimize.enable`, `optimize.group` properties through java api

**Comment by XBaith** [comment]
> image
> Still pending, I alert `optimize.enable`, `optimize.group` properties through java api

And have low performance when list optimizing tables after starting AMS, I am not sure whether issue is lead by this pr

```
2022-12-08 07:38:45,061 INFO [Metastore Scheduled Check Worker 5] [org.apache.iceberg.BaseMetastoreTableOperations] [] - Refreshing table metadata from new version: hdfs://nameservice1/user/hive/warehouse/db/table/metadata/00332-5390135f-2908-4d2c-9016-ddb42383bb6f.metadata.json
2022-12-08 07:38:51,901 WARN [Finalizer] [org.apache.iceberg.hadoop.HadoopStreams] [] - Unclosed input stream created by:
	org.apache.iceberg.hadoop.HadoopStreams$HadoopSeekableInputStream.<init>(HadoopStreams.java:81)
	org.apache.iceberg.hadoop.HadoopStreams.wrap(HadoopStreams.java:56)
	org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175)
	org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101)
	org.apache.iceberg.avro.AvroIterable.getMetadata(AvroIterable.java:66)
	org.apache.iceberg.ManifestReader.<init>(ManifestReader.java:104)
	org.apache.iceberg.ManifestFiles.read(ManifestFiles.java:87)
	org.apache.iceberg.ManifestGroup.lambda$entries$15(ManifestGroup.java:245)
	org.apache.iceberg.relocated.com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	org.apache.iceberg.util.ParallelIterable$ParallelIterator.submitNextTask(ParallelIterable.java:131)
	org.apache.iceberg.util.ParallelIterable$ParallelIterator.checkTasks(ParallelIterable.java:118)
	org.apache.iceberg.util.ParallelIterable$ParallelIterator.hasNext(ParallelIterable.java:155)
	com.netease.arctic.ams.server.optimize.IcebergMinorOptimizePlan.addOptimizeFiles(IcebergMinorOptimizePlan.java:69)
	com.netease.arctic.ams.server.optimize.BaseOptimizePlan.plan(BaseOptimizePlan.java:80)
	com.netease.arctic.ams.server.optimize.TableOptimizeItem.updateTableOptimizeStatus(TableOptimizeItem.java:418)
	com.netease.arctic.ams.server.optimize.OptimizeCheckTask.check(OptimizeCheckTask.java:59)
	com.netease.arctic.ams.server.optimize.OptimizeCheckTask.run(OptimizeCheckTask.java:47)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:750)
```

**Comment by zhoujinsong** [comment]
> > image
> > Still pending, I alert `optimize.enable`, `optimize.group` properties through java api
> 
> And have low performance when list optimizing tables after starting AMS, I am not sure whether issue is lead by this pr
> 
> ```
> 2022-12-08 07:38:45,061 INFO [Metastore Scheduled Check Worker 5] [org.apache.iceberg.BaseMetastoreTableOperations] [] - Refreshing table metadata from new version: hdfs://nameservice1/user/hive/warehouse/db/table/metadata/00332-5390135f-2908-4d2c-9016-ddb42383bb6f.metadata.json
> 2022-12-08 07:38:51,901 WARN [Finalizer] [org.apache.iceberg.hadoop.HadoopStreams] [] - Unclosed input stream created by:
> 	org.apache.iceberg.hadoop.HadoopStreams$HadoopSeekableInputStream.<init>(HadoopStreams.java:81)
> 	org.apache.iceberg.hadoop.HadoopStreams.wrap(HadoopStreams.java:56)
> 	org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175)
> 	org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101)
> 	org.apache.iceberg.avro.AvroIterable.getMetadata(AvroIterable.java:66)
> 	org.apache.iceberg.ManifestReader.<init>(ManifestReader.java:104)
> 	org.apache.iceberg.ManifestFiles.read(ManifestFiles.java:87)
> 	org.apache.iceberg.ManifestGroup.lambda$entries$15(ManifestGroup.java:245)
> 	org.apache.iceberg.relocated.com.google.common.collect.Iterators$6.transform(Iterators.java:783)
> 	org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
> 	org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
> 	org.apache.iceberg.util.ParallelIterable$ParallelIterator.submitNextTask(ParallelIterable.java:131)
> 	org.apache.iceberg.util.ParallelIterable$ParallelIterator.checkTasks(ParallelIterable.java:118)
> 	org.apache.iceberg.util.ParallelIterable$ParallelIterator.hasNext(ParallelIterable.java:155)
> 	com.netease.arctic.ams.server.optimize.IcebergMinorOptimizePlan.addOptimizeFiles(IcebergMinorOptimizePlan.java:69)
> 	com.netease.arctic.ams.server.optimize.BaseOptimizePlan.plan(BaseOptimizePlan.java:80)
> 	com.netease.arctic.ams.server.optimize.TableOptimizeItem.updateTableOptimizeStatus(TableOptimizeItem.java:418)
> 	com.netease.arctic.ams.server.optimize.OptimizeCheckTask.check(OptimizeCheckTask.java:59)
> 	com.netease.arctic.ams.server.optimize.OptimizeCheckTask.run(OptimizeCheckTask.java:47)
> 	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	java.lang.Thread.run(Thread.java:750)
> ```

It seems the result of `TableScan#planFiles` is not properly closed when optimizing iceberg tables.
@wangtaohz

**Comment by wangtaohz** [comment]
> 

What are the table properties and catalog properties?

**Comment by XBaith** [comment]
> What are the table properties and catalog properties?

image
image

**Comment by wangtaohz** [comment]
> > > image
> > > Still pending, I alert `optimize.enable`, `optimize.group` properties through java api
> > 
> > 
> > And have low performance when list optimizing tables after starting AMS, I am not sure whether issue is lead by this pr
> > ```
> > 2022-12-08 07:38:45,061 INFO [Metastore Scheduled Check Worker 5] [org.apache.iceberg.BaseMetastoreTableOperations] [] - Refreshing table metadata from new version: hdfs://nameservice1/user/hive/warehouse/db/table/metadata/00332-5390135f-2908-4d2c-9016-ddb42383bb6f.metadata.json
> > 2022-12-08 07:38:51,901 WARN [Finalizer] [org.apache.iceberg.hadoop.HadoopStreams] [] - Unclosed input stream created by:
> > 	org.apache.iceberg.hadoop.HadoopStreams$HadoopSeekableInputStream.<init>(HadoopStreams.java:81)
> > 	org.apache.iceberg.hadoop.HadoopStreams.wrap(HadoopStreams.java:56)
> > 	org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175)
> > 	org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101)
> > 	org.apache.iceberg.avro.AvroIterable.getMetadata(AvroIterable.java:66)
> > 	org.apache.iceberg.ManifestReader.<init>(ManifestReader.java:104)
> > 	org.apache.iceberg.ManifestFiles.read(ManifestFiles.java:87)
> > 	org.apache.iceberg.ManifestGroup.lambda$entries$15(ManifestGroup.java:245)
> > 	org.apache.iceberg.relocated.com.google.common.collect.Iterators$6.transform(Iterators.java:783)
> > 	org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
> > 	org.apache.iceberg.relocated.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
> > 	org.apache.iceberg.util.ParallelIterable$ParallelIterator.submitNextTask(ParallelIterable.java:131)
> > 	org.apache.iceberg.util.ParallelIterable$ParallelIterator.checkTasks(ParallelIterable.java:118)
> > 	org.apache.iceberg.util.ParallelIterable$ParallelIterator.hasNext(ParallelIterable.java:155)
> > 	com.netease.arctic.ams.server.optimize.IcebergMinorOptimizePlan.addOptimizeFiles(IcebergMinorOptimizePlan.java:69)
> > 	com.netease.arctic.ams.server.optimize.BaseOptimizePlan.plan(BaseOptimizePlan.java:80)
> > 	com.netease.arctic.ams.server.optimize.TableOptimizeItem.updateTableOptimizeStatus(TableOptimizeItem.java:418)
> > 	com.netease.arctic.ams.server.optimize.OptimizeCheckTask.check(OptimizeCheckTask.java:59)
> > 	com.netease.arctic.ams.server.optimize.OptimizeCheckTask.run(OptimizeCheckTask.java:47)
> > 	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> > 	java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> > 	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> > 	java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> > 	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> > 	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> > 	java.lang.Thread.run(Thread.java:750)
> > ```
> 
> It seems the result of `TableScan#planFiles` is not properly closed when optimizing iceberg tables. @wangtaohz

We will fix it in https://github.com/NetEase/arctic/issues/896

**Review by zhoujinsong — APPROVED** [review]
LGTM.
