### PR TITLE
[ARCTIC-1535] add new http interface for showing Optimizing processes

### LINKED ISSUE #1535: [Feature]: add self-optimize  detail in optimized tab of table
### Description

1、add detailed display on the optimized tab page, each record can be clicked to expand details. The details include various types of files involved in merging (insert/eq-delete/pos-delete/base), execution results (including exception information when execution fails), involved partition list, snapshot information, summary information, etc.
2、optional, we can  filter rows  by partition.

### Use case/motivation

1、Use these metrics to help users locate issues.
2、get the detail of the self-optimizing record

### Describe the solution

1、front end  add detail  info  after we click the  self-optimizing record.

### Subtasks

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

to resolve #1535 

## Brief change log

  - support new http interface: /optimizing-processes

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/ServerTableDescriptor.java [hunk 1]
```diff
@@ -225,29 +227,71 @@ public List<DDLInfo> getTableOperations(ServerTableIdentifier tableIdentifier) {
...
+          .limit(limit)
+          .collect(Collectors.toList());
+      if (!processIds.isEmpty()) {
+        tableOptimizingProcesses = getAs(
+            OptimizingMapper.class,
+            mapper -> mapper.selectOptimizingProcesses(catalog, db, table, processIds.get(processIds.size() - 1),
+                processIds.get(0)));
+        List<OptimizingTaskStat> optimizingTaskStats = getAs(OptimizingMapper.class,
+            mapper -> mapper.selectOptimizeTaskStats(processIds));
+        initOptimizingProcesses(tableOptimizingProcesses, optimizingTaskStats);
```
Comment (shidayang) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/ServerTableDescriptor.java:250]: This processing method is very inefficient in MySQL. Is there any other way we can do it?

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/model/TableOptimizingProcess.java [hunk 2]
```diff
@@ -125,4 +167,40 @@ public Long getTargetChangeSnapshotId() {
...
+    if (summary != null) {
+      inputBuilder.addFiles(summary.getEqualityDeleteSize(), summary.getEqDeleteFileCnt());
+      inputBuilder.addFiles(summary.getPositionalDeleteSize(), summary.getPosDeleteFileCnt());
+      inputBuilder.addFiles(summary.getRewriteDataSize(), summary.getRewriteDataFileCnt());
+      inputBuilder.addFiles(summary.getRewritePosDataSize(), summary.getReRowDeletedDataFileCnt());
+      outputBuilder.addFiles(summary.getNewFileSize(), summary.getNewFileCnt());
+    }
+    inputFiles = inputBuilder.build();
+    outputFiles = outputBuilder.build();
+  }
```
Comment (shidayang) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/model/TableOptimizingProcess.java:205]: Maybe we don't need this "init" method. We can directly parse from the summary when the "getOutputFiles" method is called.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java [hunk 3]
```diff
@@ -298,13 +297,9 @@ public void getOptimizeInfo(Context ctx) {
...
-    List<OptimizedRecord> all = tableDescriptor.getOptimizeInfo(catalog, db, table);
-    List<OptimizedRecord> result =
-        all.stream().sorted(Comparator.comparingLong(OptimizedRecord::getCommitTime).reversed())
-            .skip(offset)
-            .limit(limit)
-            .collect(Collectors.toList());
-    ctx.json(OkResponse.of(PageResult.of(result, all.size())));
+    PageResult<TableOptimizingProcess> result =
+        tableDescriptor.getOptimizingProcesses(catalog, db, table, offset, limit);
+    ctx.json(OkResponse.of(result));
```
Comment (shidayang) [inline ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java:302]: The processing logic here is inconsistent with the processing approach at line 238 in ServerTableDescriptor.java. Do we need to consider the limit restriction in the Derby database or not?

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/ServerTableDescriptor.java (hunk 1 above)
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/ServerTableDescriptor.java:250]: For MySQL, the `SELECT ... IN (items)` query using the primary key usually does not have performance issues, especially when the number of `items` is small. ( In this case, the number of `items` is page size, usually less than 100).

**Comment by zhoujinsong** [comment]
@wangtaohz Change the prefix to `[ARCTIC-1535]` in your PR's title to match the community guide.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/model/TableOptimizingProcess.java (hunk 2 above)
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/model/TableOptimizingProcess.java:205]: If we directly parse from the summary when the `getOutputFiles` method is called, the field `outputFiles` is useless, so we can remove it (the same as `inputFiles`).

So, there are two feasible designs:
 1. keep the `init` method, and keep the field `inputFiles` and `outputFiles`, 
 2. remove the `init` method, and remove the filed `inputFiles` and `outputFiles` but keep the `getXXX` method

I prefer 1, because it seems to be more clear as a class for a HTTP interface. What do you think? @shidayang

**Comment by wangtaohz** [comment]
> @wangtaohz Change the prefix to `[ARCTIC-1535]` in your PR's title to match the community guide.

 Okay, it's my negligence.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java (hunk 3 above)
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java:302]: Unless we remove support for Derby now, I think we need to consider the limit restriction in the Derby database.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java [hunk 4]
```diff
@@ -281,9 +280,9 @@ public void getUpgradeHiveTableProperties(Context ctx) throws IllegalAccessExcep
   }
 
   /**
-   * getRuntime optimize info.
+   * getRuntime list of optimizing processes.
```
[the remark this answers is not in the document]
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java:283]: OK, I will modify it.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/model/TableOptimizingProcess.java (hunk 2 above)
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/model/TableOptimizingProcess.java:165]: I have changed it.

File: ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java (hunk 3 above)
Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/TableController.java:314]: I have changed it.

File: ams/server/src/main/java/com/netease/arctic/server/persistence/mapper/OptimizingMapper.java [hunk 5]
```diff
@@ -160,6 +140,33 @@ List<TableOptimizingProcess> selectSuccessOptimizingProcesses(
...
+      @Result(property = "endTime", column = "end_time", typeHandler = Long2TsConverter.class),
+      @Result(property = "costTime", column = "cost_time"),
+      @Result(property = "status", column = "status"),
+      @Result(property = "failReason", column = "fail_reason"),
+      @Result(property = "optimizerToken", column = "optimizer_token"),
+      @Result(property = "threadId", column = "thread_id"),
+      @Result(property = "metricsSummary", column = "metrics_summary", typeHandler = JsonSummaryConverter.class),
+      @Result(property = "properties", column = "properties", typeHandler = Map2StringConverter.class)
+  })
+  List<OptimizingTaskMeta> selectOptimizeTaskStats(@Param("processIds") List<Long> processIds);
```
Comment (zhoujinsong) [inline ams/server/src/main/java/com/netease/arctic/server/persistence/mapper/OptimizingMapper.java:168]:
```suggestion
  List<OptimizingTaskMeta> selectOptimizeTaskMetas(@Param("processIds") List<Long> processIds);
```

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingProcessMeta.java [hunk 6]
```diff
@@ -1,9 +1,29 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.netease.arctic.server.optimizing;
+
+import java.util.Map;
+
+/**
+ * A simplified meta of optimizing process, not include input files.
```
Comment (zhoujinsong) [inline ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingProcessMeta.java:24]: Table `optimizing_process` did not include files information which belong to `task_runtime`.

Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingProcessMeta.java:24]: Yes, I will modify the description.

However, the `rewrite_input` is defined in the table `table_optimizing_process`, misleading me.

```
CREATE TABLE `table_optimizing_process`
(
    `process_id`                    bigint(20) NOT NULL COMMENT 'optimizing_procedure UUID',
    `table_id`                      bigint(20) NOT NULL,
    `catalog_name`                  varchar(64) NOT NULL COMMENT 'Catalog name',
    `db_name`                       varchar(128) NOT NULL COMMENT 'Database name',
    `table_name`                    varchar(128) NOT NULL COMMENT 'Table name',
    `target_snapshot_id`            bigint(20) NOT NULL,
    `target_change_snapshot_id`     bigint(20) NOT NULL,
    `status`                        varchar(10) NOT NULL COMMENT 'Direct to TableOptimizingStatus',
    `optimizing_type`               varchar(10) NOT NULL COMMENT 'Optimize type: Major, Minor',
    `plan_time`                     timestamp default CURRENT_TIMESTAMP COMMENT 'First plan time',
    `end_time`                      datetime(3) DEFAULT NULL COMMENT 'finish time or failed time',
    `fail_reason`                   varchar(4096) DEFAULT NULL COMMENT 'Error message after task failed',
    `rewrite_input`                 mediumblob DEFAULT NULL COMMENT 'rewrite files input',
    `summary`                       mediumtext COMMENT 'Max change transaction id of these tasks',
    `from_sequence`                 mediumtext COMMENT 'from or min sequence of each partition',
    `to_sequence`                   mediumtext COMMENT 'to or max sequence of each partition',
    PRIMARY KEY (`process_id`),
    KEY  `table_index` (`table_id`, `plan_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'History of optimizing after each commit';
```

**Review by zhoujinsong — APPROVED** [review]
LGTM.
