### PR TITLE
[ARCTIC-1062][AMS]Terminal support config spark properties in the local model

### LINKED ISSUE #1062: [Bug]: Spark reads the timestamp field eight hours longer than the actual Flink engine writes timestamp
### What happened?

Spark reads the timestamp field eight hours longer than the actual Flink engine writes the timestamp records.

### Affects Versions

master

### What engines are you seeing the problem on?

Flink, Spark

### How to reproduce

1. create catalog arctic With ('type'='arctic','metastore.url'='thrift://***:18312/mix_iceberg_catalog_simple');
2. create table arctic.flink_test.pulsar_pk (id int, name string, dt timestamp, primary key(id) not enforced) with ('log-store.enabled'='true','log-store.type'='pulsar','log-store.topic'='without_partition','log-store.address'='pulsar://***:16650','properties.pulsar.admin.adminUrl'='http://***:8180');
3. CREATE TABLE cdc_source(
  id      INT,
  name    STRING,
  op_time STRING
) WITH (
    'connector' = 'socket',
    'hostname' = 'localhost',
    'port' = '9999',
    'format' = 'changelog-csv',
    'changelog-csv.column-delimiter' = '|'
);
4. insert into arctic.flink_test.kafka_pk /*+ OPTIONS('arctic.emit.mode'='file') */
 SELECT id,
        name,
        CAST(TO_TIMESTAMP(op_time) AS TIMESTAMP(6)) ts
 FROM cdc_source;

open a socket producer: nc -lk 9999 
according to the [quick demo](https://arctic.netease.com/ch/quickstart/quick-demo/#step-2-execute-flink-upsert), write three records.
```
INSERT|4|rock|2022-07-02 09:01:00
INSERT|5|jack|2022-07-02 12:11:40
INSERT|6|mars|2022-07-02 11:19:10
```

5.  SELECT * FROM arctic.flink_test.pulsar_pk /*+ OPTIONS('arctic.read.mode'='file','scan.startup.mode'='earliest') */;
6. Open the Arctic web dashboard, open a Terminal tab, use mix_iceberg_catalog_simple catalog, and edit the SQL: select * from flink_test.pulsar_pk;

### Relevant log output

_No response_

### Anything else

popo_2023-02-07  11-10-49
popo_2023-02-07  11-12-04
popo_2023-02-07  11-12-29

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hellojinsilei**
## Why are the changes needed?

fix #1062 

## Brief change log

  - add config key prefix of terminal: SPARK_CONF = "spark."

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes)
 
Terminal  is executed in local mode, you can configure Spark properties

arctic.ams.terminal.backend: local
arctic.ams.terminal.local.spark.driver.extraJavaOptions:  -Duser.timezone=UTC
arctic.ams.terminal.local.spark.executor.extraJavaOptions:  -Duser.timezone=UTC
arctic.ams.terminal.local.spark.sql.session.timeZone: UTC
arctic.ams.terminal.local.spark.sql.iceberg.handle-timestamp-without-timezone=false

### CODE REVIEW

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/config/ArcticMetaStoreConf.java [hunk 1]
```diff
@@ -188,6 +188,7 @@ public class ArcticMetaStoreConf {
    * config key prefix of terminal
    */
   public static final String TERMINAL_PREFIX = "arctic.ams.terminal.";
+  public static final String SPARK_CONF = "spark.sql";
```
Comment (baiyangtx) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/config/ArcticMetaStoreConf.java:191]: Spark conf properties should start with   `spark.`

**Review by baiyangtx — CHANGES_REQUESTED** [review]

**Review by baiyangtx — APPROVED** [review]

File: ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java [hunk 2]
```diff
@@ -194,6 +194,7 @@ public static void beforeAllTest() throws Exception {
     com.netease.arctic.ams.server.config.Configuration configuration =
         new com.netease.arctic.ams.server.config.Configuration();
     configuration.setString(ArcticMetaStoreConf.DB_TYPE, "derby");
+    configuration.setString("arctic.ams.terminal.local.spark.sql.session.timeZone", "UTC");
```
Comment (Aireed) [inline ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java:197]: Please  repalce the key with  a static variable  like  'ArcticMetaStoreConf.DB_TYPE'

Comment (hellojinsilei) [reply ams/ams-server/src/test/java/com/netease/arctic/ams/server/AmsTestBase.java:197]: @Aireed CC 
I think this property is not a standard configuration for ArcticMetaStore, I add  this property just to test Spark

**Review by Aireed — APPROVED** [review]
LGTM
