### PR TITLE
[ARCTIC-1378] Incorrect data synchronization caused the data of the arctic base table to be overwritten

### LINKED ISSUE #1378: [Bug]: Incorrect data synchronization caused the data of the arctic base table to be overwritten
### What happened?

The arctic base table was overwritten due to incorrect data synchronization after an empty hive table was upgraded to an arctic table. Because empty hive tables don't have full 'table.partition-properties' when upgraded, But we need 'hive-location' and 'transient-time' in 'table.partition-properties' to decide if we want to sync our data

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

_No response_

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hameizi**
## Why are the changes needed?
resolve #1378

## Brief change log

Set partition properties for all partitions even if there are no files under the partition when upgrading a Hive table to an Arctic table.

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: hive/src/main/java/com/netease/arctic/hive/utils/UpgradeHiveTableUtil.java [hunk 1]
```diff
@@ -136,6 +143,7 @@ private static void hiveDataMigration(
       }
     }
     HiveMetaSynchronizer.syncHiveDataToArctic(arcticTable, arcticHiveCatalog.getHMSClient());
+    fillPartitionProperties(arcticTable, arcticHiveCatalog, hiveTable);
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/utils/UpgradeHiveTableUtil.java:146]: May need to reload `hiveTable` after `HiveMetaSynchronizer#syncHiveDataToArctic` is called.

**Comment by zhoujinsong** [comment]
@hameizi  Did you reproduce the issue locally and validate that it has indeed been fixed with the new code?

**Review by zhoujinsong — APPROVED** [review]
LGTM.
