### PR TITLE
[ARCTIC-1369][Hive]Fix bug: AlterTableAddColumn not support field with uppercase letters in Spark

### LINKED ISSUE #1369: [Bug]: AlterTableAddColumn not support field with uppercase letters in Spark
### What happened?

Adding fields with uppercase letters in spark will throw an exception:
image

### Affects Versions

0.3.2

### What engines are you seeing the problem on?

Spark

### How to reproduce

Execute sql: Alter table test_table add COLUMNS(bRand STRING ,app_partner STRING ,os STRING);

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hellojinsilei**
## Why are the changes needed?

fix #1369 

This bug caused by Hive tables are not sensitive to schema case, but our iceberg table is sensitive to case, which results in errors during Hive schema sync to Arcitc
## Brief change log
change in com.netease.arctic.hive.utils.HiveMetaSynchronizer#updateStructSchema

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by baiyangtx — APPROVED** [review]

File: hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java [hunk 1]
```diff
@@ -95,6 +95,14 @@ private static boolean updateStructSchema(TableIdentifier tableIdentifier, Updat
     for (int i = 0; i < hiveStruct.fields().size(); i++) {
       Types.NestedField hiveField = hiveStruct.fields().get(i);
       Types.NestedField icebergField = icebergStruct.field(hiveField.name());
+      // to check if lowercase matches
+      List<Types.NestedField> fields = icebergStruct
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:99]: I suggest replacing the process of getting iceberg fields here with traversing all Hive fields, and checking that the matched result is no more than 1.

File: hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java [hunk 2]
```diff
@@ -92,32 +92,39 @@ public static void syncHiveSchemaToArctic(ArcticTable table, HMSClientPool hiveC
...
+      if (fields.isEmpty()) {
         updateSchema.addColumn(parentName, hiveField.name(), hiveField.type(), hiveField.doc());
         update = true;
         LOG.info("Table {} sync new hive column {} to arctic", tableIdentifier, hiveField);
-      } else if (!icebergField.type().equals(hiveField.type()) ||
-          !Objects.equals(icebergField.doc(), (hiveField.doc()))) {
-        if (hiveField.type().isPrimitiveType() && icebergField.type().isPrimitiveType()) {
-          if (TypeUtil.isPromotionAllowed(icebergField.type().asPrimitiveType(), hiveField.type().asPrimitiveType())) {
+      } else {
+        Types.NestedField icebergField = fields.get(0);
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:106]: If multiple fields are matched, I think an error should be thrown instead of using the first one directly.

**Review by zhoujinsong — APPROVED** [review]
