### PR TITLE
[ARCTIC-812]:Add flink sink properties to table default

### LINKED ISSUE #812: [Bug]: Flink connector commits empty snapshot.
### What happened?

image

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

Flink

### How to reproduce

Create a flink job writing to the arctic table and no data incoming.  The flink job will commit an empty snapshot at every checkpoint.

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by baiyangtx**
## Why are the changes needed?

fix #812 
Avoid empty snapshots in the AMS transaction page.

## Brief change log

- Add a default table property `flink.max-continuous-empty-commits=Integer.MAX_VALUE`

## How was this patch tested?

-  Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)

### CODE REVIEW

**Review by zhoujinsong — COMMENTED** [review]
LGTM.But do you think we need to display this property in table detail page on AMS Dashboard? If not , you may want add this property into `TableProperties#READ_PROTECTED_PROPERTIES`.

File: core/src/main/java/com/netease/arctic/catalog/BaseArcticCatalog.java [hunk 1]
```diff
@@ -661,6 +661,7 @@ protected void fillTableProperties(TableMeta meta) {
       meta.putToProperties(TableProperties.TABLE_CREATE_TIME, String.valueOf(System.currentTimeMillis()));
       meta.putToProperties(org.apache.iceberg.TableProperties.FORMAT_VERSION, "2");
       meta.putToProperties(org.apache.iceberg.TableProperties.METADATA_DELETE_AFTER_COMMIT_ENABLED, "true");
+      meta.putToProperties("flink.max-continuous-empty-commits", Integer.MAX_VALUE + "");
```
Comment (zhoujinsong) [inline core/src/main/java/com/netease/arctic/catalog/BaseArcticCatalog.java:664]:
```suggestion
      meta.putToProperties("flink.max-continuous-empty-commits", String.valueOf(Integer.MAX_VALUE));
```

**Comment by zhoujinsong** [comment]
@baiyangtx  There are some conflicts with master, can you fix it?

**Review by zhoujinsong — APPROVED** [review]
LGTM.
