### PR TITLE
[ARCTIC-917][HIVE]Fix bug: Data are written repeatedly after the Spark Executor failover

### LINKED ISSUE #917: [Bug][Spark]: The data are written repeatedly after the Spark Executor failover
### What happened?

When after running the Spark insert command, more data is written. And on Spark UI, there are many Executors that have failover. 
If Executor does not failover, the amount of data observed is correct

### Affects Versions

0.3.2

### What engines are you seeing the problem on?

Spark

### How to reproduce

Running the Spark insert command, if the executor has failover, the problem will be reproduced

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hellojinsilei**
## Why are the changes needed?

fix #917 
Solution: handle orphan files when overwrite commit.

During spark overwrite is committing, the spark driver will list partition files for new creation partitions or partitions that have a new location, the spark driver needs to delete files which not exist in the overwrite operation added files set. This action will happen before the iceberg table commit.

## Brief change log
Add a property: delete-untracked-hive-file (default=false)

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: hive/src/main/java/com/netease/arctic/hive/op/ReplaceHivePartitions.java [hunk 1]
```diff
@@ -221,6 +226,25 @@ private void applyHivePartitions() {
...
+   * @param dataFiles
+   */
+  private void checkOrphanFilesAndDelete(String partitionLocation, List<DataFile> dataFiles) {
+    if (!table.io().isEmptyDirectory(partitionLocation)) {
+      List<String> filePathCollect = dataFiles.stream()
+          .map(dataFile -> dataFile.path().toString()).collect(Collectors.toList());
+      List<FileStatus> exisitedFiles = table.io().list(partitionLocation);
+      for (FileStatus filePath: exisitedFiles) {
+        if (!filePathCollect.contains(filePath.getPath().toString())) {
+          table.io().deleteFile(String.valueOf(filePath.getPath().toString()));
```
Comment (shendanfengg) [inline hive/src/main/java/com/netease/arctic/hive/op/ReplaceHivePartitions.java:241]: When deleting a file, try to print why it was deleted and the name of the deleted file to the WARN log.

File: hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java [hunk 2]
```diff
@@ -261,6 +268,29 @@ private void checkCreatePartitionDataFiles(List<DataFile> addFiles, String parti
...
+      if (!table.io().isEmptyDirectory(partitionLocation)) {
+        List<String> addFilesPathCollect = addFiles.stream()
+            .map(dataFile -> dataFile.path().toString()).collect(Collectors.toList());
+        List<String> deleteFilesPathCollect = deleteFiles.stream()
+            .map(deleteFile -> deleteFile.path().toString()).collect(Collectors.toList());
+        List<FileStatus> exisitedFiles = table.io().list(partitionLocation);
+        for (FileStatus filePath: exisitedFiles) {
+          if (!addFilesPathCollect.contains(filePath.getPath().toString()) &&
+              !deleteFilesPathCollect.contains(filePath.getPath().toString())) {
+            table.io().deleteFile(String.valueOf(filePath.getPath().toString()));
```
Comment (shendanfengg) [inline hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java:287]: Log printing is also required here

File: hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java [hunk 3]
```diff
@@ -98,6 +99,12 @@ public void commit() {
       this.partitionToCreate = getCreatePartition(this.partitionToDelete);
     }
 
+    if (PropertyUtil.propertyAsBoolean(
+        table.properties(),
+        HiveTableProperties.DELETE_UNTRACKED_HIVE_FILE,
+        HiveTableProperties.DELETE_UNTRACKED_HIVE_FILE_DEFAULT)) {
+      checkOrphanFilesAndDelete();
```
Comment (shendanfengg) [inline hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java:106]: When a user inserts data using native HiveSQL and wants to take advantage of Arctic's Hive Data sync feature, will this data be cleaned up?

**Comment by Aireed** [comment]
cc @baiyangtx ,  The proposal we discussed a few days ago is different from this one. Is the modification here part of your proposal?

File: hive/src/main/java/com/netease/arctic/hive/HiveTableProperties.java [hunk 4]
```diff
@@ -55,5 +55,8 @@ public class HiveTableProperties {
   public static final String PARQUET_INPUT_FORMAT = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat";
   public static final String PARQUET_OUTPUT_FORMAT = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat";
   public static final String PARQUET_ROW_FORMAT_SERDE = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe";
+
+  public static final String DELETE_UNTRACKED_HIVE_FILE = "delete.untracked.hive.file";
+  public static final boolean DELETE_UNTRACKED_HIVE_FILE_DEFAULT = false;
```
Comment (baiyangtx) [inline hive/src/main/java/com/netease/arctic/hive/HiveTableProperties.java:60]: This is not a table property

File: hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java (hunk 3 above)
Comment (baiyangtx) [reply hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java:105]: This clean action will only happen when spark insert overwrite be executed.

File: hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java [hunk 5]
```diff
@@ -261,6 +268,30 @@ private void checkCreatePartitionDataFiles(List<DataFile> addFiles, String parti
...
   }
 
+  /**
+   * check files in the partition, and delete orphan files
+   */
+  private void checkOrphanFilesAndDelete() {
+    List<String> partitionsToCheck = this.partitionToCreate.values()
+        .stream().map(partition -> partition.getSd().getLocation()).collect(Collectors.toList());
+    for (String partitionLocation: partitionsToCheck) {
+      if (!table.io().isEmptyDirectory(partitionLocation)) {
```
Comment (baiyangtx) [inline hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java:277]: why call this method?  use `table.io.list` instead.  
don't call the unnecessary hadoop rpc.

**Review by baiyangtx — CHANGES_REQUESTED** [review]

File: hive/src/test/java/com/netease/arctic/hive/op/TestRewritePartitions.java [hunk 6]
```diff
@@ -173,6 +175,38 @@ public void testExceptionAddFileWithDifferentLocation() throws TException {
     Assert.assertThrows(CannotAlterHiveLocationException.class, replacePartitions::commit);
   }
 
+  @Test
+  public void testPreCommitCheck() throws TException {
```
Comment (baiyangtx) [inline hive/src/test/java/com/netease/arctic/hive/op/TestRewritePartitions.java:179]: maybe should be testCleanOrphanFileWhenCommit.

File: hive/src/test/java/com/netease/arctic/hive/op/TestRewriteFiles.java [hunk 7]
```diff
@@ -375,6 +380,45 @@ public void testExceptionDeleteCreateSamePartition() throws TException {
     Assert.assertThrows(CannotAlterHiveLocationException.class, rewriteFiles::commit);
   }
 
+  @Test
+  public void testPreCommitCheck() throws TException {
```
Comment (baiyangtx) [inline hive/src/test/java/com/netease/arctic/hive/op/TestRewriteFiles.java:384]: testCleanOrphanFileWhenCommit

File: hive/src/test/java/com/netease/arctic/hive/op/TestOverwriteFiles.java [hunk 8]
```diff
@@ -415,6 +419,39 @@ public void testOverwriteCommitHMSFailed() throws TException {
     hiveTable.setTableName(testHiveTable.id().getTableName());
     hms.getClient().alter_table(testHiveTable.id().getDatabase(), "new_table", hiveTable);
   }
+  @Test
+  public void testPreCommitCheck() throws TException {
```
Comment (baiyangtx) [inline hive/src/test/java/com/netease/arctic/hive/op/TestOverwriteFiles.java:423]: testCleanOrphanFileWhenCommit

File: spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/KeyedSparkBatchWrite.java [hunk 9]
```diff
@@ -148,8 +150,9 @@ public DataWriterFactory createBatchWriterFactory(PhysicalWriteInfo info) {
 
     @Override
     public void commit(WriterCommitMessage[] messages) {
-      RewritePartitions rewritePartitions = table.newRewritePartitions();
+      KeyedPartitionRewrite rewritePartitions = (KeyedPartitionRewrite) table.newRewritePartitions();
       rewritePartitions.withTransactionId(txId);
+      rewritePartitions.set(DELETE_UNTRACKED_HIVE_FILE, "true");
```
Comment (baiyangtx) [inline spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/KeyedSparkBatchWrite.java:155]: Why need a Convert here ?

File: spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/UnkeyedSparkBatchWrite.java [hunk 10]
```diff
@@ -133,6 +134,7 @@ public DataWriterFactory createBatchWriterFactory(PhysicalWriteInfo info) {
     @Override
     public void commit(WriterCommitMessage[] messages) {
       ReplacePartitions replacePartitions = table.newReplacePartitions();
+      replacePartitions.set(DELETE_UNTRACKED_HIVE_FILE, "true");
```
Comment (baiyangtx) [inline spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/UnkeyedSparkBatchWrite.java:137]: replacePartition dosen't need this property, it will always check orphan files.

File: spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/KeyedSparkBatchWrite.java (hunk 9 above)
Comment (baiyangtx) [reply spark/v3.1/spark/src/main/java/com/netease/arctic/spark/writer/KeyedSparkBatchWrite.java:155]: replacePartition dosen't need this property, it will always check orphan files.

**Review by baiyangtx — CHANGES_REQUESTED** [review]

**Review by baiyangtx — APPROVED** [review]

**Comment by baiyangtx** [comment]
> cc @baiyangtx , The proposal we discussed a few days ago is different from this one. Is the modification here part of your proposal?

Here is a solution for both spark and optimizer

**Comment by hzluting** [comment]
I think this doesn't handle the unPartition table
