### PR TITLE
[ARCTIC-1474]: Self-Optimizing cached table list not fetched correctly 

### LINKED ISSUE #1474: [Bug]: Self-Optimizing cached table list not fetched correctly
### What happened?

image
image
image
As you can see my Arctic table actually exists in AMS, but getTableOptimizeItem is still unable to load the table, a behaviour that may prevent Self-Optimizing from progressing smoothly
image
There is a greater risk that this function will be quoted in more than one place

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. Not sure of the exact method of recurrence

### Relevant log output

```shell
2023-05-26 13:59:43,537 ERROR [Metastore Scheduled Table Runtime Data Expire Worker 0] [com.netease.arctic.ams.server.service.impl.RuntimeDataExpireService] [] - arctic_da_luna.da_luna.arctic_xxxxx failed to expire and clear table_task_history table
com.netease.arctic.ams.api.NoSuchObjectException: can't find table arctic_da_luna.da_luna.arctic_xxxxx
        at com.netease.arctic.ams.server.optimize.OptimizeService.getTableOptimizeItem(OptimizeService.java:278) ~[arctic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.service.impl.RuntimeDataExpireService.lambda$expire$0(RuntimeDataExpireService.java:74) ~[arctic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_261]
        at com.netease.arctic.ams.server.service.impl.RuntimeDataExpireService.expire(RuntimeDataExpireService.java:70) ~[arctic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.service.impl.RuntimeDataExpireService.doExpire(RuntimeDataExpireService.java:60) ~[arctic-ams-server-0.4.1-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_261]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
```

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Aireed**
fix #1474 

## Why are the changes needed?

OptimizeService::getTableOptimizeItem  doesn't check the table in optimizeTables.  
RuntimeDataExpireService::expire  will trigger refreshAndListTables when can't get the TableOptimizeItem, i  think we should refresh first and then do expire logic.

## Brief change log

1. call   refreshAndListTables to get tables which need to expire optimize_history
2、Improve logging when TableOptimizeItem cannot be found.

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/RuntimeDataExpireService.java [hunk 1]
```diff
@@ -65,27 +65,34 @@ public void doExpire() {
...
-        TableOptimizeRuntime tableOptimizeRuntime =
-            optimizeService.getTableOptimizeItem(identifier).getTableOptimizeRuntime();
-        tableTaskHistoryService.expireTaskHistory(identifier,
-            tableOptimizeRuntime.getLatestTaskPlanGroup(),
-            System.currentTimeMillis() - this.taskHistoryDataExpireInterval);
-      } catch (Exception e) {
-        LOG.error("{} failed to expire and clear table_task_history table", identifier, e);
-      }
-    });
+    if (optimizeTables != null && optimizeTables.size() > 0) {
```
Comment (wangtaohz) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/RuntimeDataExpireService.java:70]: Maybe we should just remove `optimizeService.getTableOptimizeItem(identifier).getTableOptimizeRuntime()` from `RuntimeDataExpireService`, because not cleaning the task history with the `latestTaskPlanGroup` 7 days ago brings almost no benefits.

**Review by wangtaohz — APPROVED** [review]
