### PR TITLE
[ARCTIC-1708] [Bug]: When using a partition name with uppercase letters in the mixed hive format, it leads to an exceptio

### LINKED ISSUE #1708: [Bug]: When using a partition name with uppercase letters in the mixed hive format, it leads to an exception
### What happened?

When I create a table under a mixed hive catalog with the following ddl
create table xxx.xxx (
    id int,
    Name string, 
    primary key (id)
) using arctic 
partitioned by(identity(Name));
image
As shown this case is not as expected because hive does not have a capitalisation field.
And when I run insert overwrite on this table, it throws an ArrayIndexOutOfBoundsException.

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

Core

### How to reproduce

1.Select a catalog in mixed hive format and create a table ddl as follows
create table xxx.xxx (
    id int,
    Name string, 
    primary key (id)
) using arctic 
partitioned by (identity(Name));
2.Viewing the table detail
3.Execute in the terminal 
insert overwrite xxx.xxx values (1, 'bob);

### Relevant log output

```shell
2023/07/17 19:17:22 org.apache.spark.SparkException: Writing job aborted.
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:388)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2$(WriteToDataSourceV2Exec.scala:336)
	at org.apache.spark.sql.execution.datasources.v2.OverwritePartitionsDynamicExec.writeWithV2(WriteToDataSourceV2Exec.scala:278)
	at org.apache.spark.sql.execution.datasources.v2.OverwritePartitionsDynamicExec.run(WriteToDataSourceV2Exec.scala:287)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:40)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:40)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:46)
	at org.apache.spark.sql.Dataset.$anonfun$logicalPlan$1(Dataset.scala:228)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3687)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3685)
	at org.apache.spark.sql.Dataset.(Dataset.scala:228)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:615)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:610)
	at com.netease.arctic.ams.server.terminal.local.LocalTerminalSession.executeStatement(LocalTerminalSession.java:65)
	at com.netease.arctic.ams.server.terminal.TerminalSessionContext$ExecutionTask.executeStatement(TerminalSessionContext.java:275)
	at com.netease.arctic.ams.server.terminal.TerminalSessionContext$ExecutionTask.execute(TerminalSessionContext.java:238)
	at com.netease.arctic.ams.server.terminal.TerminalSessionContext$ExecutionTask.lambda$get$0(TerminalSessionContext.java:199)
	at com.netease.arctic.table.TableMetaStore.doAsUgi(TableMetaStore.java:365)
	at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873)
	at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:345)
	at com.netease.arctic.ams.server.terminal.TerminalSessionContext$ExecutionTask.get(TerminalSessionContext.java:191)
	at com.netease.arctic.ams.server.terminal.TerminalSessionContext$ExecutionTask.get(TerminalSessionContext.java:162)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.iceberg.data.GenericRecord.set(GenericRecord.java:129)
	at com.netease.arctic.utils.ArcticDataFiles.data(ArcticDataFiles.java:117)
	at com.netease.arctic.utils.TablePropertyUtil.decodePartitionProperties(TablePropertyUtil.java:79)
	at com.netease.arctic.op.PartitionPropertiesUpdate.apply(PartitionPropertiesUpdate.java:90)
	at com.netease.arctic.op.PartitionPropertiesUpdate.commit(PartitionPropertiesUpdate.java:112)
	at com.netease.arctic.op.PartitionTransactionOperation.commit(PartitionTransactionOperation.java:96)
	at com.netease.arctic.spark.writer.KeyedSparkBatchWrite$DynamicOverwrite.commit(KeyedSparkBatchWrite.java:198)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:371)
	... 37 more
```

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nicochen**
## Why are the changes needed?

fix #1708

## Brief change log

1.  Use caseInsensitiveSelect when generating GenericRecord
2.  Lowercase partition names when creating mixed hive tables

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java [hunk 1]
```diff
@@ -151,6 +151,6 @@ private static GenericRecord genericRecord(PartitionSpec spec) {
         return s.name();
       }
     }).collect(Collectors.toList());
-    return GenericRecord.create(spec.schema().select(collect));
+    return GenericRecord.create(spec.schema().caseInsensitiveSelect(collect));
```
Comment (zhoujinsong) [inline core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java:154]: Assuming that the partition field is all lowercase is risky, as it may cause problems in systems that support uppercase fields, leading to incorrect parsing of partition data through the partition path.

File: hive/src/main/java/org/apache/iceberg/IcebergSchemaUtil.java [hunk 2]
```diff
@@ -30,7 +30,7 @@ public class IcebergSchemaUtil {
   public static PartitionSpec copyPartitionSpec(PartitionSpec partitionSpec, Schema copySchema) {
     PartitionSpec.Builder builder = PartitionSpec.builderFor(copySchema);
     partitionSpec.fields().forEach(partitionField -> {
-      builder.add(partitionField.sourceId(), partitionField.name(), partitionField.transform());
+      builder.add(partitionField.sourceId(), partitionField.name().toLowerCase(), partitionField.transform());
```
Comment (zhoujinsong) [inline hive/src/main/java/org/apache/iceberg/IcebergSchemaUtil.java:33]: I suggest clarifying the behavior and reasons for changing partition fields to lowercase in the Java doc.

File: core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java (hunk 1 above)
Comment (nicochen) [reply core/src/main/java/com/netease/arctic/utils/ArcticDataFiles.java:154]: This method is defined by iceberg as
/**
   * Creates a projection schema for a subset of columns, selected by name.
   *
   * <p>Names that identify nested fields will select part or all of the field's top-level column.
   *
   * @param names String names for selected columns
   * @return a projection schema from this schema, by name
   */
In general, iceberg schema doesn't allow to see fields called 'PartitionName' and 'partitionname' at the same time, but if I don't use caseInsensitiveSelect, it will construct an incorrect GenericRecord if I query 'partitionname'  with 'PartitionName' .
So I don't think this change should be risky.

File: hive/src/main/java/org/apache/iceberg/IcebergSchemaUtil.java (hunk 2 above)
Comment (nicochen) [reply hive/src/main/java/org/apache/iceberg/IcebergSchemaUtil.java:33]: Okay, I'll add some notes
