### PR TITLE
[ARCTIC-924][Hive] When AMS runs for a period of time and then cannot connect to HMS

### LINKED ISSUE #924: [Bug]: When AMS runs for a period of time and then cannot connect to HMS
### What happened?

image
image
When AMS runs for a period of time and then cannot connect to HMS.
Then, no operations can be executed, and the database and table cannot be obtained. 
Optimize also stops.

### Affects Versions

0.3.x

### What engines are you seeing the problem on?

Core

### How to reproduce

_No response_

### Relevant log output

```shell
2022-12-13 09:55:01,821 ERROR [JettyServerThreadPool-138139] [com.netease.arctic.table.TableMetaStore] [] - run with catalog ugi request failed. UGI is recsys/dm@HADOOP.HZ.NETEASE.COM (auth:KERBEROS)
org.apache.iceberg.hive.RuntimeMetaException: Failed to connect to Hive Metastore
        at com.netease.arctic.hive.ArcticHiveClientPool.lambda$newClient$0(ArcticHiveClientPool.java:73) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316) ~[arctic-core-0.3.2-20221202.072950-12.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_101]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873) ~[hadoop-common-2.9.2.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314) ~[arctic-core-0.3.2-20221202.072950-12.jar:?]
        at com.netease.arctic.hive.ArcticHiveClientPool.newClient(ArcticHiveClientPool.java:59) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.hive.ArcticHiveClientPool.newClient(ArcticHiveClientPool.java:38) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at org.apache.iceberg.ClientPoolImpl.get(ClientPoolImpl.java:118) ~[iceberg-core-0.12.0.jar:?]
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:49) ~[iceberg-core-0.12.0.jar:?]
        at com.netease.arctic.hive.CachedHiveClientPool.lambda$run$2(CachedHiveClientPool.java:76) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316) ~[arctic-core-0.3.2-20221202.072950-12.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_101]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873) ~[hadoop-common-2.9.2.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314) ~[arctic-core-0.3.2-20221202.072950-12.jar:?]
        at com.netease.arctic.hive.CachedHiveClientPool.run(CachedHiveClientPool.java:76) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.hive.utils.HiveTableUtil.getAllHiveTables(HiveTableUtil.java:156) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.ams.server.controller.TableController.getTableList(TableController.java:456) ~[arctic-ams-server-0.3.2-20221206.073402-15.jar:?]
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_101]
at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89) ~[javalin-4.6.1.jar:4.6.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58) ~[javalin-4.6.1.jar:4.6.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551) ~[jetty-servlet-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52) ~[javalin-4.6.1.jar:4.6.1]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489) ~[jetty-servlet-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.Server.handle$sentryProxy(Server.java:501) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.Server.handle(Server.java) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272) [jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: Could not connect to meta store using any of the URIs provided. Most recent failure: org.apache.thrift.transport.TTransportException: GSS initiate failed
        at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:226)
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:308)
        at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:38)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:52)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:49)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport.open(TUGIAssumingTransport.java:49)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:477)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:285)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:210)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.iceberg.common.DynConstructors$Ctor.newInstanceChecked(DynConstructors.java:60)
        at org.apache.iceberg.common.DynConstructors$Ctor.newInstance(DynConstructors.java:73)
        at com.netease.arctic.hive.ArcticHiveClientPool.lambda$newClient$0(ArcticHiveClientPool.java:62)
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873)
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314)
        at com.netease.arctic.hive.ArcticHiveClientPool.newClient(ArcticHiveClientPool.java:59)
        at com.netease.arctic.hive.ArcticHiveClientPool.newClient(ArcticHiveClientPool.java:38)
        at org.apache.iceberg.ClientPoolImpl.get(ClientPoolImpl.java:118)
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:49)
        at com.netease.arctic.hive.CachedHiveClientPool.lambda$run$2(CachedHiveClientPool.java:76)
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873)
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314)
        at com.netease.arctic.hive.CachedHiveClientPool.run(CachedHiveClientPool.java:76)
        at com.netease.arctic.hive.utils.HiveTableUtil.getAllHiveTables(HiveTableUtil.java:156)
        at com.netease.arctic.ams.server.controller.TableController.getTableList(TableController.java:456)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
        at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle$sentryProxy(Server.java:501)
        at org.eclipse.jetty.server.Server.handle(Server.java)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.lang.Thread.run(Thread.java:745)

        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:525) ~[hive-metastore-2.1.1.jar:2.1.1]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:285) ~[hive-metastore-2.1.1.jar:2.1.1]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:210) ~[hive-metastore-2.1.1.jar:2.1.1]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
        at org.apache.iceberg.common.DynConstructors$Ctor.newInstanceChecked(DynConstructors.java:60) ~[iceberg-common-0.12.0.jar:?]
        at org.apache.iceberg.common.DynConstructors$Ctor.newInstance(DynConstructors.java:73) ~[iceberg-common-0.12.0.jar:?]
        at com.netease.arctic.hive.ArcticHiveClientPool.lambda$newClient$0(ArcticHiveClientPool.java:62) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        ... 80 more

2022-12-13 09:55:00,683 ERROR [JettyServerThreadPool-211351] [AmsRestServer] [] - Failed to handle request
java.lang.RuntimeException: Failed to list databases
        at com.netease.arctic.hive.catalog.ArcticHiveCatalog.listDatabases(ArcticHiveCatalog.java:85) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.ams.server.controller.TableController.getDatabaseList(TableController.java:487) ~[arctic-ams-server-0.3.2-20221206.073402-15.jar:?]
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_101]
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85) ~[javalin-4.6.1.jar:4.6.1]
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89) ~[javalin-4.6.1.jar:4.6.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58) ~[javalin-4.6.1.jar:4.6.1]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551) ~[jetty-servlet-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52) ~[javalin-4.6.1.jar:4.6.1]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489) ~[jetty-servlet-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.Server.handle$sentryProxy(Server.java:501) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.Server.handle(Server.java) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272) [jetty-server-9.4.30.v20200611.jar:9.4.30.v20200611]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.30.v20200611.jar:9.4.30.v20200611]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: Could not connect to meta store using any of the URIs provided. Most recent failure: org.apache.thrift.transport.TTransportException: GSS initiate failed
        at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:226)
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:308)
        at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:38)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:52)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:49)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport.open(TUGIAssumingTransport.java:49)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:477)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:285)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:210)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.iceberg.common.DynConstructors$Ctor.newInstanceChecked(DynConstructors.java:60)
        at org.apache.iceberg.common.DynConstructors$Ctor.newInstance(DynConstructors.java:73)
        at com.netease.arctic.hive.ArcticHiveClientPool.lambda$newClient$0(ArcticHiveClientPool.java:62)
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873)
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314)
        at com.netease.arctic.hive.ArcticHiveClientPool.newClient(ArcticHiveClientPool.java:59)
        at com.netease.arctic.hive.ArcticHiveClientPool.newClient(ArcticHiveClientPool.java:38)
        at org.apache.iceberg.ClientPoolImpl.get(ClientPoolImpl.java:118)
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:49)
        at com.netease.arctic.hive.CachedHiveClientPool.lambda$run$2(CachedHiveClientPool.java:76)
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873)
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314)
        at com.netease.arctic.hive.CachedHiveClientPool.run(CachedHiveClientPool.java:76)
        at com.netease.arctic.hive.catalog.ArcticHiveCatalog.listDatabases(ArcticHiveCatalog.java:83)
        at com.netease.arctic.ams.server.controller.TableController.getDatabaseList(TableController.java:487)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
        at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
        at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
        at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle$sentryProxy(Server.java:501)
        at org.eclipse.jetty.server.Server.handle(Server.java)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
 at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.lang.Thread.run(Thread.java:745)

        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:525) ~[hive-metastore-2.1.1.jar:2.1.1]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:285) ~[hive-metastore-2.1.1.jar:2.1.1]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:210) ~[hive-metastore-2.1.1.jar:2.1.1]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
        at org.apache.iceberg.common.DynConstructors$Ctor.newInstanceChecked(DynConstructors.java:60) ~[iceberg-common-0.12.0.jar:?]
        at org.apache.iceberg.common.DynConstructors$Ctor.newInstance(DynConstructors.java:73) ~[iceberg-common-0.12.0.jar:?]
        at com.netease.arctic.hive.ArcticHiveClientPool.lambda$newClient$0(ArcticHiveClientPool.java:62) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316) ~[arctic-core-0.3.2-20221202.072950-12.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_101]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873) ~[hadoop-common-2.9.2.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314) ~[arctic-core-0.3.2-20221202.072950-12.jar:?]
        at com.netease.arctic.hive.ArcticHiveClientPool.newClient(ArcticHiveClientPool.java:59) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.hive.ArcticHiveClientPool.newClient(ArcticHiveClientPool.java:38) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at org.apache.iceberg.ClientPoolImpl.get(ClientPoolImpl.java:118) ~[iceberg-core-0.12.0.jar:?]
        at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:49) ~[iceberg-core-0.12.0.jar:?]
        at com.netease.arctic.hive.CachedHiveClientPool.lambda$run$2(CachedHiveClientPool.java:76) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316) ~[arctic-core-0.3.2-20221202.072950-12.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_101]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873) ~[hadoop-common-2.9.2.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314) ~[arctic-core-0.3.2-20221202.072950-12.jar:?]
        at com.netease.arctic.hive.CachedHiveClientPool.run(CachedHiveClientPool.java:76) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.hive.catalog.ArcticHiveCatalog.listDatabases(ArcticHiveCatalog.java:83) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        ... 63 more

2022-12-13 09:55:01,307 ERROR [Metastore Scheduled Check Worker 9] [com.netease.arctic.table.TableMetaStore] [] - run with catalog ugi request failed. UGI is recsys/dm@HADOOP.HZ.NETEASE.COM (auth:K
ERBEROS)
org.apache.iceberg.exceptions.RuntimeIOException: Failed to refresh the table
        at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:121) ~[iceberg-core-0.12.0.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.current(HadoopTableOperations.java:80) ~[iceberg-core-0.12.0.jar:?]
        at org.apache.iceberg.hadoop.HadoopTables.load(HadoopTables.java:86) ~[iceberg-core-0.12.0.jar:?]
        at com.netease.arctic.hive.catalog.ArcticHiveCatalog.lambda$loadKeyedTable$3(ArcticHiveCatalog.java:163) ~[arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:316) ~[arctic-core-0.3.2-20221202.072950-12.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at javax.security.auth.Subject.doAs(Subject.java:360) [?:1.8.0_101]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873) [hadoop-common-2.9.2.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:314) [arctic-core-0.3.2-20221202.072950-12.jar:?]
        at com.netease.arctic.hive.catalog.ArcticHiveCatalog.loadKeyedTable(ArcticHiveCatalog.java:163) [arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.hive.catalog.ArcticHiveCatalog.loadKeyedTable(ArcticHiveCatalog.java:67) [arctic-hive-0.3.2-20221202.073003-12.jar:?]
        at com.netease.arctic.catalog.BaseArcticCatalog.loadTableByMeta(BaseArcticCatalog.java:177) [arctic-core-0.3.2-20221202.072950-12.jar:?]
        at com.netease.arctic.catalog.BaseArcticCatalog.loadTable(BaseArcticCatalog.java:170) [arctic-core-0.3.2-20221202.072950-12.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.refresh(TableOptimizeItem.java:262) [arctic-ams-server-0.3.2-20221206.073402-15.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.tryRefresh(TableOptimizeItem.java:252) [arctic-ams-server-0.3.2-20221206.073402-15.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.getArcticTable(TableOptimizeItem.java:222) [arctic-ams-server-0.3.2-20221206.073402-15.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.updateTableOptimizeStatus(TableOptimizeItem.java:381) [arctic-ams-server-0.3.2-20221206.073402-15.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCheckTask.check(OptimizeCheckTask.java:58) [arctic-ams-server-0.3.2-20221206.073402-15.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCheckTask.run(OptimizeCheckTask.java:47) [arctic-ams-server-0.3.2-20221206.073402-15.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "sloth5.jd.163.org/10.196.85.29"; destination host is: "hadoop3003.jd.163.org":8020;
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:805) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1453) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy188.getFileInfo(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:796) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy190.getFileInfo(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1649) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1529) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1627) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.getMetadataFile(HadoopTableOperations.java:240) ~[iceberg-core-0.12.0.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:101) ~[iceberg-core-0.12.0.jar:?]
        ... 25 more
Caused by: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
        at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:760) ~[hadoop-common-2.9.2.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_101]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:723) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:817) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1568) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1399) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy188.getFileInfo(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:796) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy190.getFileInfo(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1649) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1529) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1627) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.getMetadataFile(HadoopTableOperations.java:240) ~[iceberg-core-0.12.0.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:101) ~[iceberg-core-0.12.0.jar:?]
        ... 25 more
Caused by: javax.security.sasl.SaslException: GSS initiate failed
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211) ~[?:1.8.0_101]
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:407) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:618) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$2200(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:804) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:800) ~[hadoop-common-2.9.2.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_101]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:799) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1568) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1399) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy188.getFileInfo(Unknown Source) ~[?:?]
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:796) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy190.getFileInfo(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1649) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1529) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1627) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.getMetadataFile(HadoopTableOperations.java:240) ~[iceberg-core-0.12.0.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:101) ~[iceberg-core-0.12.0.jar:?]
        ... 25 more
Caused by: javax.security.sasl.SaslException: GSS initiate failed
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211) ~[?:1.8.0_101]
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:407) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:618) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$2200(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:804) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:800) ~[hadoop-common-2.9.2.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_101]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:799) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1568) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1399) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy188.getFileInfo(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:796) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy190.getFileInfo(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1649) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1529) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1627) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.getMetadataFile(HadoopTableOperations.java:240) ~[iceberg-core-0.12.0.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:101) ~[iceberg-core-0.12.0.jar:?]
... 25 more
Caused by: org.ietf.jgss.GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147) ~[?:1.8.0_101]
        at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122) ~[?:1.8.0_101]
        at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187) ~[?:1.8.0_101]
        at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224) ~[?:1.8.0_101]
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212) ~[?:1.8.0_101]
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179) ~[?:1.8.0_101]
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192) ~[?:1.8.0_101]
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:407) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:618) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$2200(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:804) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:800) ~[hadoop-common-2.9.2.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
        at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_101]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:799) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:412) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1568) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1399) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:227) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy188.getFileInfo(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:796) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359) ~[hadoop-common-2.9.2.jar:?]
        at com.sun.proxy.$Proxy190.getFileInfo(Unknown Source) ~[?:?]
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1649) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1529) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1526) ~[hadoop-hdfs-client-2.9.2.jar:?]
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1627) ~[hadoop-common-2.9.2.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.getMetadataFile(HadoopTableOperations.java:240) ~[iceberg-core-0.12.0.jar:?]
        at org.apache.iceberg.hadoop.HadoopTableOperations.refresh(HadoopTableOperations.java:101) ~[iceberg-core-0.12.0.jar:?]
        ... 25 more

```

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by shendanfengg**
## Why are the changes needed?
fix #924 

## Brief change log

  - Set the default retry to true when the CachedHiveClientPool executes an HMS-related operation

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? ( no)

### CODE REVIEW

File: hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java [hunk 1]
```diff
@@ -73,7 +73,7 @@ private synchronized void init() {
   @Override
   public <R> R run(Action<R, HMSClient, TException> action) throws TException, InterruptedException {
     try {
-      return tableMetaStore.doAs(() -> clientPool().run(action));
+      return tableMetaStore.doAs(() -> clientPool().run(action, true));
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java:76]: Should we change the `retryByDefault` parameter when constructing `ArcticHiveClientPool`, and keep this `run` method using the default configuration?

**Review by zhoujinsong — APPROVED** [review]
LGTM.
