### PR TITLE
[ARCTIC-1103][AMS] Clear the optimizing tasks when the optimizing commit failed

### LINKED ISSUE #1103: [Improvement][AMS]: Automatic retry optimizing if commit failed
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now, the optimizing will be hanged when the optimizing commit failed.

### How should we improve?

We can clear the task and automatic retry optimizing rather than waiting for the manual operation.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hzluting**
## Why are the changes needed?
fix #1103 

## Brief change log

  - *Clear the optimizing tasks when the optimizing commit failed*
  - *Clear the optimizing tasks when the table has failed tasks after max retry*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by wangtaohz** [comment]
After clearing the optimizing tasks, the `currentChangeSnapshotId` and `currentSnapshotId` in `TableOptimizeRuntime` should also be reset, or it will skip the next plan if the table does not change.

It's better to be fixed in this PR.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java [hunk 1]
```diff
@@ -673,10 +673,14 @@ private void optimizeTasksClear(BasicOptimizeCommit optimizeCommit) {
...
       try {
+        // reset snapshot id in table runtime, because the tasks were cleared rather than committed.
+        // So need to plan again.
+        tableOptimizeRuntime.setCurrentSnapshotId(TableOptimizeRuntime.INVALID_SNAPSHOT_ID);
+        tableOptimizeRuntime.setCurrentChangeSnapshotId(TableOptimizeRuntime.INVALID_SNAPSHOT_ID);
         // persist partition optimize time
         tableOptimizeRuntimeMapper.updateTableOptimizeRuntime(tableOptimizeRuntime);
       } catch (Throwable t) {
-        LOG.warn("failed to persist tableOptimizeRuntime after commit, ignore. " + getTableIdentifier(), t);
+        LOG.warn("failed to persist tableOptimizeRuntime after commit failed, ignore. " + getTableIdentifier(), t);
```
Comment (wangtaohz) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java:683]: There is a standard procedure to update tableOptimizeRuntime to keep the consistency of memory and sysdb.

We should stick to it.

The procedure is like
```
oldRuntime = tableOptimizeRuntime.clone();
try {
    // update tableOptimizeRuntime

} catch () {
    tableOptimizeRuntime.restore(oldRuntime);
    sqlSession.rollback(true);
}
```

BTW, there are too `failed` in the warn log.

Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java]: OK

**Review by wangtaohz — APPROVED** [review]
LGTM

**Comment by hzluting** [comment]
Now, there are two main exceptions causing optimizing hang. These exceptions can continue running if we clear the tasks.
1. Commit exception
- Missing required files to delete
- Found new delete for replaced data file
- For the unKeyed table, the file cache isn't the latest, handling the hive partition in the commit will throw an exception
- It took a long time to complete the task, the snapshot with the plan expired when committing

2. Execute exception
- If the task executes timeout, we modify the property named "self-optimizing.execute.timeout", it can continue running
- If the task plan with incorrect file info, causing the task throws the exception "file not found"

cc @wangtaohz @shendanfengg
Do you have any new situations to add?

**Comment by wangtaohz** [comment]
> 2.Execute exception
If the task executes timeout, we modify the property named "self-optimizing.execute.timeout", it can continue running If the task plan with incorrect file info, causing the task throws the exception "file not found"

I support it as a default behavior to clean all tasks after any task fails(after retry for several times).

Even if it can't recover automatically after cleaning and planning, it's better than keeping hang up.

And this issue https://github.com/NetEase/arctic/issues/1060 could be fixed here.

**Comment by hzluting** [comment]
> > 2.Execute exception
> > If the task executes timeout, we modify the property named "self-optimizing.execute.timeout", it can continue running If the task plan with incorrect file info, causing the task throws the exception "file not found"
> 
> I support it as a default behavior to clean all tasks after any task fails(after retry for several times).
> 
> Even if it can't recover automatically after cleaning and planning, it's better than keeping hang up.
> 
> And this issue #1060 could be fixed here.

OK

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java [hunk 2]
```diff
@@ -661,9 +662,9 @@ public void addNewOptimizeTasks(List<BasicOptimizeTask> newOptimizeTasks)
     }
   }
 
-  private void optimizeTasksClear(BasicOptimizeCommit optimizeCommit) {
+  public void optimizeTasksClear(Boolean refreshOptimizeStatus) {
```
Comment (wangtaohz) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java:665]: Now, `optimizeTasksClear` also clears tasks in `Executing` status, we have to handle the `optimize_task_history` of these tasks, or it will affect the quota occupation of this table.

BTW, `boolean` may be better than`Boolean`.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java [hunk 3]
```diff
@@ -173,14 +173,14 @@ private void clearTableCache(TableIdentifier tableIdentifier) {
...
     optimizeQueueService.release(tableIdentifier);
     try {
-      deleteTableOptimizeRuntime(tableIdentifier);
+      tableItem.optimizeTasksClear(false);
     } catch (Throwable t) {
-      LOG.debug("failed to delete  " + tableIdentifier + " runtime, ignore", t);
+      LOG.debug("failed to delete " + tableIdentifier + " optimize task, ignore", t);
     }
     try {
-      tableItem.clearOptimizeTasks();
```
Comment (wangtaohz) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java:181]: There are two similar methods in `TableOptimizeItem`:
- clearOptimizeTasks
- optimizeTasksClear

I think we should remove one of them.

**Review by wangtaohz — COMMENTED** [review]
@hzluting I add some comments, plesase take a look.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java (hunk 2 above)
Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java]: OK

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java (hunk 3 above)
Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/OptimizeService.java:181]: OK

**Comment by XBaith** [comment]
> 2. Execute exception
> 
> * If the task executes timeout, we modify the property named "self-optimizing.execute.timeout", it can continue running
> * If the task plan with incorrect file info, causing the task throws the exception "file not found"
> 
> cc @wangtaohz @shendanfengg Do you have any new situations to add?
* HDFS cluster network issue also lead to failure to obtain file info

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java [hunk 4]
```diff
@@ -794,13 +798,22 @@ private void optimizeTasksCommitted(BasicOptimizeCommit optimizeCommit,
...
+        long endTime = System.currentTimeMillis();
         tasks.values().stream().flatMap(Collection::stream).map(OptimizeTaskItem::getTaskId)
             .forEach(optimizeTaskId -> {
               OptimizeTaskItem removed = optimizeTasks.remove(optimizeTaskId);
               if (removed != null) {
                 removedList.add(removed);
                 optimizeTasksMapper.deleteOptimizeTask(optimizeTaskId.getTraceId());
                 internalTableFilesMapper.deleteOptimizeTaskFile(optimizeTaskId);
+
+                // set end time and cost time in optimize_task_history
```
Comment (wangtaohz) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java:810]: Why should we set the cost time after committing?

Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java]: It should be in the optimizeTasksClear method.

**Comment by XBaith** [comment]
> Now, there are two main exceptions causing optimizing hang. These exceptions can continue running if we clear the tasks.
> 
> 1. Commit exception
> 
> 2. Execute exception
> 
> cc @wangtaohz @shendanfengg Do you have any new situations to add?
`org.apache.hadoop.security.AccessControlException: Permission denied` exception can occur in both cases.

**Review by wangtaohz — APPROVED** [review]
LGTM

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java [hunk 5]
```diff
@@ -922,6 +928,27 @@ public void checkTaskExecuteTimeout() {
...
 
+  /**
+   * If task execute failed after max retry, clear tasks.
+   */
+  public void clearFailedTasks() {
+    tasksLock.lock();
+    try {
+      int maxRetry = optimizeMaxRetry();
+      Optional<OptimizeTaskItem> failedTask =
+          optimizeTasks.values().stream().findAny().filter(task -> task.getOptimizeRuntime().getRetry() > maxRetry);
```
Comment (zhongqishang) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java:939]: @hzluting 
- Should `findAny()` be placed at the end
- Add filter `OptimizeStatus.Failed == task.getOptimizeRuntime().getStatus()`

What do you think?

**Review by zhongqishang — COMMENTED** [review]
Sorry for the late comment.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java (hunk 5 above)
Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java:939]: Yes, thank you for your comment

Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java:939]: @zhongqishang I fix it in #1168
