### PR TITLE
[ARCTIC-1385][Bug]: fix transaction and action fields value error

### LINKED ISSUE #1385: [Bug]: The column ‘_transaction_id’ and '_change_action' will be null when querying change table with spark
### What happened?

The column ‘_transaction_id’ and '_change_action' will be null when querying change table

### Affects Versions

0.4.1

### What engines are you seeing the problem on?

Spark

### How to reproduce

Using spark to query change table with ‘_transaction_id’  '_change_action' columns. 
such as:
`select _transaction_id, _change_action from {tableName}.change`

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by baiyangtx**
## Why are the changes needed?
 
fix #1385 
 
## Brief change log

- Add class ArcticChangeTableScan which extend Iceberg  DataTableScan.
- Add class ArcticManifestGroup which extend iceberg ManifestGroup
- Use ArcticChangeTableScan instead of BasicChangeTableIncreamentScan
- Remove BasicChangeTableIncreamentScan

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

 
- [X] Run test locally before making a pull request

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/ArcticChangeTableScan.java [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+    super(ops, table, schema, context);
+  }
+
+  @Override
+  public ArcticChangeTableScan useSnapshot(long scanSnapshotId) {
+    super.useSnapshot(scanSnapshotId);
+    Schema snapshotSchema = SnapshotUtil.schemaFor(table(), scanSnapshotId);
+    return newRefinedScan(
+        tableOps(), table(), snapshotSchema, context().useSnapshotId(scanSnapshotId));
+  }
```
Comment (shidayang) [inline core/src/main/java/org/apache/iceberg/ArcticChangeTableScan.java:54]: This method is the same as super class, May be don't need to rewrite

File: core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+  ArcticManifestGroup scanMetrics(ScanMetrics metrics) {
+    super.scanMetrics(metrics);
+    return this;
+  }
+
+  @Override
+  ArcticManifestGroup ignoreDeleted() {
+    super.ignoreDeleted();
+    return this;
+  }
```
Comment (shidayang) [inline core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java:69]: These method don't need to rewrite

**Review by shidayang — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+import java.util.Map;
+
+public class ArcticManifestGroup extends ManifestGroup {
+
+  ArcticManifestGroup(FileIO io, Iterable<ManifestFile> dataManifests, Iterable<ManifestFile> deleteManifests) {
+    super(io, dataManifests, deleteManifests);
+  }
+
+  @Override
+  ArcticManifestGroup caseSensitive(boolean newCaseSensitive) {
```
Comment (zhoujinsong) [inline core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java:36]: What is the reason to override these methods if we just call the super method?

File: core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+    return plan(ArcticManifestGroup::createContentFileWithSequence);
+  }
+
+  private static CloseableIterable<ContentFileScanTaskWithSequence> createContentFileWithSequence(
+      CloseableIterable<ManifestEntry<DataFile>> entries, TaskContext ctx) {
+    return CloseableIterable.transform(
+        entries,
+        entry -> {
+          DataFile dataFile = entry.file().copy(ctx.shouldKeepStats());
+          return new ContentFileScanTaskWithSequence(dataFile, entry.fileSequenceNumber());
```
Comment (zhoujinsong) [inline core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java:82]: we may use the data sequence number rather than file sequence number?

Comment (zhoujinsong) [reply core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java:82]: Besides,  is the data sequence number value would be null if the entry status is `ADD`?

File: core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+        });
+  }
+
+
+  public static class ContentFileScanTaskWithSequence implements ScanTask {
```
Comment (zhoujinsong) [inline core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java:87]: Can you simplify the class name to make it consist of 3/4 word?

File: core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java (hunk 2 above)
Comment (baiyangtx) [reply core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java:69]: the return type is different. if we don't overwrite the method, the chain call is not available

File: core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java (hunk 3 above)
Comment (baiyangtx) [reply core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java:36]: the return type is different. if we don't overwrite the method, the chain call is not available.

File: core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java (hunk 4 above)
Comment (baiyangtx) [reply core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java:82]: the entry's file seq inherit from mainfest list if the status is ADDED

Comment (baiyangtx) [reply core/src/main/java/org/apache/iceberg/ArcticManifestGroup.java:82]: > we may use the data sequence number rather than file sequence number?

The code I refactored used the file seq num, what's the different?

**Review by zhoujinsong — APPROVED** [review]
LGTM.
