### PR TITLE
[ARCTIC-1107] Fix the problem that PartitionPropertiesUpdate can't remove key

### LINKED ISSUE #1107: [Bug][Core]: The PartitionPropertiesUpdate can't remove partition properties key
### What happened?

When I use the PartitionPropertiesUpdate#remove method, it is not effective.

### Affects Versions

0.3.0

### What engines are you seeing the problem on?

_No response_

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hzluting**
## Why are the changes needed?
fix #1107 

## Brief change log

  - *add remove the key to the removeProperties*

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: core/src/test/java/com/netease/arctic/op/UpdatePartitionPropertiesTest.java [hunk 1]
```diff
@@ -60,4 +60,20 @@ public void testUpdatePartitionPropertiesInTx() {
...
   }
+
+  @Test
+  public void testRemovePartitionProperties() {
+    StructLikeMap<Map<String, String>> partitionProperties = getArcticTable().asUnkeyedTable().partitionProperty();
+    Assert.assertEquals(0, partitionProperties.size());
+    StructLike p0 = TestHelpers.Row.of(1200);
+    getArcticTable().asUnkeyedTable().updatePartitionProperties(null).set(p0, "key", "value").commit();
+    partitionProperties = getArcticTable().asUnkeyedTable().partitionProperty();
+    Assert.assertEquals(1, partitionProperties.size());
```
Comment (zhoujinsong) [inline core/src/test/java/com/netease/arctic/op/UpdatePartitionPropertiesTest.java:71]: Maybe we should check the size of p0's properties with code:
```
Assert.assertEquals(1, partitionProperties.get(p0).size())
```

File: core/src/test/java/com/netease/arctic/op/UpdatePartitionPropertiesTest.java [hunk 2]
```diff
@@ -60,4 +60,20 @@ public void testUpdatePartitionPropertiesInTx() {
...
+    Assert.assertEquals("value", partitionProperties.get(p0).get("key"));
+
+    getArcticTable().asUnkeyedTable().updatePartitionProperties(null).remove(p0, "key").commit();
+    partitionProperties = getArcticTable().asUnkeyedTable().partitionProperty();
+    Assert.assertEquals(1, partitionProperties.size());
```
Comment (zhoujinsong) [inline core/src/test/java/com/netease/arctic/op/UpdatePartitionPropertiesTest.java:76]: Maybe we should check the size of p0's properties with code:
```
Assert.assertEquals(0, partitionProperties.get(p0).size())
```

**Review by zhoujinsong — APPROVED** [review]
