### PR TITLE
[ARCTIC-1730] Add a ceche when building IcebergDeleteFile in IcebergTableFileScanHelper.scan to prevent too many generated IcebergDeleteFiles

### LINKED ISSUE #1730: [Bug]:  When the table with deletefile in V2 format plan, the phenomenon of Icebergdeletefile amplification will appear
### What happened?

image
IcebergDeleteFile wraps GenericDeleteFile, but because there are duplicate deletefile objects in FileScanTask, GenericDeleteFile will be wrapped repeatedly, resulting in the explosion of the number of IcebergDeleteFile objects
image
image

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

in any case

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
## Why are the changes needed?
fix #1730 

## Brief change log
Add a ceche when building IcebergDeleteFile in IcebergTableFileScanHelper.scan to prevent too many generated IcebergDeleteFiles

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/scan/IcebergTableFileScanHelper.java [hunk 1]
```diff
@@ -31,12 +31,14 @@
...
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
 import java.io.IOException;
 import java.io.UncheckedIOException;
 import java.util.List;
+import java.util.Map;
 import java.util.stream.Collectors;
 
 public class IcebergTableFileScanHelper implements TableFileScanHelper {
```
Comment (huyuanfeng2018) [inline ams/server/src/main/java/com/netease/arctic/server/optimizing/scan/IcebergTableFileScanHelper.java:44]: I'm not sure if KeyedTableFileScanHelper and UnkeyedTableFileScanHelper will have this situation, because I don't have a corresponding environment locally.

Comment (baiyangtx) [reply ams/server/src/main/java/com/netease/arctic/server/optimizing/scan/IcebergTableFileScanHelper.java:44]: I think this problem will be much better in mixed-format, because in mixed-format, delete files are organized by node hierarchy and will not intersect with many data files. And when planning, tasks are also organized by nodes, not files like in an iceberg table.

**Review by baiyangtx — APPROVED** [review]
LGTM.

Thank you for your contribution!  This PR should significantly reduce the memory usage during the optimizing plan process for iceberg tables with many delete files.
