### PR TITLE
[ARCTIC-1227] should not be case sensitive when reading the hive upgrade table schema

### LINKED ISSUE #1227: [Bug]: should not be case sensitive when reading the hive upgrade table schema
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

optimize after upgrading the arctic table will fail if the case of the field names in the hive table schema and the parquet schema do not match
### How should we improve?
should not be case sensitive when reading the hive upgrade table schema

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hameizi**
## Why are the changes needed?

resolve #1227 

## Brief change log

Case differences are ignored when matching parquet file schema and namemapping

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Review by shidayang — APPROVED** [review]

File: hive/src/test/java/org/apache/iceberg/parquet/TestAdaptHiveReadConf.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+import org.apache.parquet.schema.PrimitiveType;
+import org.apache.parquet.schema.Type;
+import org.apache.parquet.schema.Types;
+import org.junit.Assert;
+import org.junit.Test;
+
+public class TestAdaptHiveReadConf {
+
+  @Test
+  public void testConvertNameMapping() {
```
Comment (zhoujinsong) [inline hive/src/test/java/org/apache/iceberg/parquet/TestAdaptHiveReadConf.java:35]: We may add more struct types in test cases like struct, map, and array.

File: hive/pom.xml [hunk 2]
```diff
@@ -123,6 +123,7 @@
                 <configuration>
                     <includes>
                         <include>**/ArcticHiveTestMain.java</include>
+                        <include>**/TestAdaptHiveReadConf.java</include>
```
Comment (zhoujinsong) [inline hive/pom.xml:126]: Or we can add this new test case to the `ArcticHiveTestMain` suit?

File: hive/src/test/java/org/apache/iceberg/parquet/TestAdaptHiveReadConf.java (hunk 1 above)
Comment (hameizi) [reply hive/src/test/java/org/apache/iceberg/parquet/TestAdaptHiveReadConf.java]: added in new commit
