### PR TITLE
[ARCTIC-1095][AMS] Add the sequence number for the native iceberg table when the major optimizing commit

### LINKED ISSUE #1095: [Bug]: Full compaction completed, cannot commit
### What happened?

Native iceberg format table 
Set configration `write.metadata.metrics.default=full`

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

```shell
2023-02-10 16:12:56,679 ERROR [Metastore Scheduled Commit Worker 4] [com.netease.arctic.table.TableMetaStore] [] - run with ugi request failed.
org.apache.iceberg.exceptions.ValidationException: Cannot commit, found new delete for replaced data file: com.netease.arctic.data.file.DataFileWithSequence@4af4abb4
        at org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:46) ~[iceberg-api-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:371) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:316) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.BaseRewriteFiles.validate(BaseRewriteFiles.java:108) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:162) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:283) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190) ~[iceberg-core-0.13.2.jar:?]
        at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:282) ~[iceberg-core-0.13.2.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.lambda$majorCommit$8(IcebergOptimizeCommit.java:236) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAsUgi(TableMetaStore.java:355) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:335) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_141]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_141]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1873) ~[hadoop-common-2.9.2.jar:?]
        at com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:335) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.io.ArcticHadoopFileIO.doAs(ArcticHadoopFileIO.java:177) ~[arctic-core-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.majorCommit(IcebergOptimizeCommit.java:235) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.IcebergOptimizeCommit.commit(IcebergOptimizeCommit.java:100) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.TableOptimizeItem.commitOptimizeTasks(TableOptimizeItem.java:938) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at com.netease.arctic.ams.server.optimize.OptimizeCommitWorker.run(OptimizeCommitWorker.java:49) ~[arctic-ams-server-0.5.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_141]
```

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hzluting**
## Why are the changes needed?
fix #1095 

## Brief change log
  - *Add the sequence number for the native iceberg table when the major optimizing commit*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
@hzluting Hi, When committing major optimizing on an iceberg format table for one single partition, will the replaced delete files be deleted as there are other data files under other partitions which's sequence number is lower than replaced ones?

**Review by wangtaohz — APPROVED** [review]
LGTM

**Comment by hzluting** [comment]
> 

OK, I will add the removing DeleteFiles.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java [hunk 1]
```diff
@@ -214,13 +214,29 @@ private void majorCommit(ArcticTable arcticTable,
...
+        rewriteDataFiles.validateFromSnapshot(baseSnapshotId);
+        long sequenceNumber = arcticTable.asUnkeyedTable().snapshot(baseSnapshotId).sequenceNumber();
+        rewriteDataFiles.rewriteFiles(deleteDataFiles, addDataFiles, sequenceNumber);
+      } else {
+        rewriteDataFiles.rewriteFiles(deleteDataFiles, addDataFiles);
+      }
+      rewriteDataFiles.set(SnapshotSummary.SNAPSHOT_PRODUCER, CommitMetaProducer.OPTIMIZE.name());
+      rewriteDataFiles.commit();
+
+      // remove DeleteFiles additional, because DeleteFiles maybe not existed
```
Comment (XBaith) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java:228]: Could you explain what `DeleteFiles maybe not existed` means?

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java [hunk 2]
```diff
@@ -214,13 +214,29 @@ private void majorCommit(ArcticTable arcticTable,
...
 
       // rewrite DataFiles
-      RewriteFiles rewriteFiles = baseArcticTable.newRewrite();
-      rewriteFiles.set(SnapshotSummary.SNAPSHOT_PRODUCER, CommitMetaProducer.OPTIMIZE.name());
+      RewriteFiles rewriteDataFiles = baseArcticTable.newRewrite();
       if (baseSnapshotId != TableOptimizeRuntime.INVALID_SNAPSHOT_ID) {
-        rewriteFiles.validateFromSnapshot(baseSnapshotId);
+        rewriteDataFiles.validateFromSnapshot(baseSnapshotId);
+        long sequenceNumber = arcticTable.asUnkeyedTable().snapshot(baseSnapshotId).sequenceNumber();
+        rewriteDataFiles.rewriteFiles(deleteDataFiles, addDataFiles, sequenceNumber);
```
Comment (XBaith) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java:221]: Hi @hzluting 
So now we use the snapshot id instead of creating a new one? 
major commit: sequence_num_1
current snapshot: sequence_num_1, but it has eq-delete files
when we commit the rewrite files, iceberg validate new deletes for these data files, then throw the Exception.
Is my understanding correct?

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java (hunk 1 above)
Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java:228]: Iceberg will auto-remove the DeleteFiles according to the sequence number.
The detail is in MergingSnapshotProducer#apply(), Iceberg will drop DeleteFiles that are older than the min Data sequence number.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java (hunk 2 above)
Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java:221]: The snapshot is still create a new one, but the sequence number of the DataFiles in this commit is the same as the snapshot when optimizing plan. So the eq-delete files produced by flink in optimizing process still affect the new DataFiles produced by optimizing, we don't need to check whether has new eq-delete files.
Once we commit the rewrite files with the sequence number, Iceberg won't validate eq-delete files, and we can commit success.(The detail is in MergingSnapshotProducer#validateNoNewDeletesForDataFiles())

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java (hunk 1 above)
Comment (XBaith) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java:228]: Maybe we can explain some details, because it will mislead devlopler.For example:
> Don't need to manually delete delete files if they were droped in last commit

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java (hunk 2 above)
Comment (XBaith) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java:221]: > 

Thanks for your comment! It makes sense

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java (hunk 1 above)
Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/IcebergOptimizeCommit.java:228]: OK
