### PR TITLE
[ARCTIC-955][ARCTIC-916] Load sequence number once in optimize plan

### LINKED ISSUE #955: [Bug]: Optimize status hangs in pending and minor
### What happened?

Hi, Optimize Iceberg has encountered two problems, and I haven't found the problem for a long time:
1. optimize group 1: The optimizer is still alive but the OptimizeQueue has no plan log, which means the queue no longer works? (It will no longer work after merging 2-3 tables successfully)

3. optimize group 2: optimize does not respond for a long time after the execution of minor, although its file size is very small. (Some tables succeed, some tables hang on or timeout retry)

And I'm not sure the bug ocurred by my change which I drop all status in `BaseFileScan` to reduce jvm heap memory(BTW, It does save a lot of memory. If this has no impact on optimization, I will trigger a new PR for this.). 

### Affects Versions

master/0.4.x

### What engines are you seeing the problem on?

AMS

### How to reproduce

just optimize a certain number of iceberg tables

### Relevant log output

_No response_

### Anything else

image
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by XBaith**
## Why are the changes needed?

Avoid scanning holl tables in each partition to reduce heap memory. 
fix #955 issue 1 and decrease full gc times (mentioned in #916  )

## Brief change log

In some cases, tables have more than a hundred thousand partitions (12 months and 16 bucket sizes), and scanning the table per partition will be very expensive. Actually we only need to load the current file and sequence number mapping in one optimized plan.

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by XBaith** [comment]
cc @wangtaohz @hzluting

**Comment by wangtaohz** [comment]
Thanks for your work! 
And I think it will bring a significant performance improvement when planning with many partitions.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java [hunk 1]
```diff
@@ -440,7 +441,10 @@ public void updateTableOptimizeStatus() {
               getIcebergMinorPlan(fileScanTasks, -1, System.currentTimeMillis(), partitionIsRunning);
           List<BaseOptimizeTask> minorTasks = minorPlan.plan();
           // pending for minor optimize
-          if (CollectionUtils.isNotEmpty(minorTasks)) {
+          if (CollectionUtils.isNotEmpty(minorTasks) && TableOptimizeStatusUtil.in(
```
Comment (wangtaohz) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/TableOptimizeItem.java:444]: It may be related to this issue https://github.com/NetEase/arctic/issues/959, we'd better discuss it under this issue, and then put a new PR to fix it.

**Review by wangtaohz — APPROVED** [review]
