### PR TITLE
[ARCTIC-814] Fix optimize can't stop when the change store only has eq-delete files and the base store has no files

### LINKED ISSUE #814: [Improvement]: Optimize can't stop when the change store only has eq-delete files and the base store has no files
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Even if the minor optimize output is nothing, the commit still should update "max-txId" in partition properties.

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hzluting**
## Why are the changes needed?
fix #814 

## Brief change log

  - *Even if the minor optimize output is nothing, the commit still updates "max-txId" in partition properties*

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java [hunk 1]
```diff
@@ -204,11 +207,11 @@ private void minorCommit(ArcticTable arcticTable,
       overwriteBaseFiles.set(SnapshotSummary.SNAPSHOT_PRODUCER, CommitMetaProducer.OPTIMIZE.name());
       overwriteBaseFiles.validateNoConflictingAppends(Expressions.alwaysFalse());
       AtomicInteger addedPosDeleteFile = new AtomicInteger(0);
-      StructLikeMap<Long> oldPartitionMaxIds =
-          TablePropertyUtil.getPartitionMaxTransactionId(arcticTable.asKeyedTable());
       minorAddFiles.forEach(contentFile -> {
         // if partition min transactionId isn't bigger than max transactionId in partitionProperty,
         // the partition files is expired
+        StructLikeMap<Long> oldPartitionMaxIds =
```
Comment (zhoujinsong) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java:213]: Why should we read the properties every time for a new file?

Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java]: It's no need. I moved it by mistake.

**Review by wangtaohz — APPROVED** [review]
LGTM

**Review by zhoujinsong — APPROVED** [review]
LGTM.
