### PR TITLE
[ARCTIC-1649] Add detailed fail reason for optimizing commit failure

### LINKED ISSUE #1649: [Improvement]: The fail reason in Web UI is too vague when optimizing commit failed
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

image

The fail reason only shows 'unexpected commit error' when optimizing commit failed.

### How should we improve?

Display more detailed failure information.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

fix #1649 

## Brief change log

  - Add detailed fail reason for optimizing commit failure
  - move `ExceptionUtil` from module `optimizer` to `core`

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **no**)

### CODE REVIEW

**Comment by wangtaohz** [comment]
The result after fixed
image

File: ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java [hunk 1]
```diff
@@ -499,7 +500,7 @@ public void commit() {
       } catch (Exception e) {
         LOG.warn("{} Commit optimizing failed ", tableRuntime.getTableIdentifier(), e);
         status = Status.FAILED;
-        failedReason = e.getMessage();
+        failedReason = ExceptionUtil.getErrorMessage(e, 4000);
```
Comment (XBaith) [inline ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java:503]: Can you append some errors from up level? For example: UnKeyedTableCommit#replaceFiles?

Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/optimizing/OptimizingQueue.java:503]: For the convenience of troubleshooting, I have displayed as much information as possible here, including the exception stack.

Although it may appear a bit verbose on the current page, these exception details will be moved to the subsequent process detail page.

**Review by zhoujinsong — APPROVED** [review]
LGTM.
