### PR TITLE
[ARCTIC-938][Optimize] Deleting invalid data files when the major optimize commit throw ValidationException

### LINKED ISSUE #938: [Bug][AMS]: Optimize will delete valid files when optimize execute repeated commit in some exceptional cases
### What happened?

When optimize commit to iceberg success but don't clear the optimize tasks in AMS and DB(such as restarting AMS). It will try to commit again, and the iceberg will throw the ValidationException(Missing required files to delete), the AMS will delete the new files produced by this tasks, but these new files are valid for the iceberg table in actuality and can't delete.
So, we should check whether these new files are already committed to the iceberg table.

### Affects Versions

0.3.0

### What engines are you seeing the problem on?

_No response_

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hzluting**
## Why are the changes needed?
fix #938 

## Brief change log

  - *remove the logic of deleting the files produced by minor optimize*
  - *check whether the data files are valid before deleting files*

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java [hunk 1]
```diff
@@ -422,4 +425,31 @@ private static Set<ContentFile<?>> selectMajorOptimizeDeletedFiles(BaseOptimizeT
...
+  private static Set<String> getCommittedDataFilesFromSnapshotId(ArcticTable arcticTable, long snapshotId) {
+    UnkeyedTable baseArcticTable;
+    if (arcticTable.isKeyedTable()) {
+      baseArcticTable = arcticTable.asKeyedTable().baseTable();
+    } else {
+      baseArcticTable = arcticTable.asUnkeyedTable();
+    }
+
+    long currentSnapshotId = UnKeyedTableUtil.getSnapshotId(baseArcticTable);
+    if (currentSnapshotId == snapshotId) {
```
Comment (wangtaohz) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java:438]: The following `SnapshotUtil.ancestorsBetween` has handled this case, so it could be removed.

Comment (wangtaohz) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java:438]: And what if `snapshotId == TableOptimizeRuntime.INVALID_SNAPSHOT_ID`, which will happen after planning on an empty base table?

Maybe we should change `snapshotId` from `TableOptimizeRuntime.INVALID_SNAPSHOT_ID` to `null` before we call `SnapshotUtil.ancestorsBetween`.

File: ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizeCommit.java [hunk 2]
```diff
@@ -199,6 +199,78 @@ public void testEmptyTargetFilesMajorOptimizeCommit() throws Exception {
...
+    testKeyedTable.baseTable().newScan().planFiles()
+        .forEach(fileScanTask -> {
+          newDataFilesPath.add((String) fileScanTask.file().path());
+          fileScanTask.deletes().forEach(deleteFile -> newDeleteFilesPath.add((String) deleteFile.path()));
+        });
+    Assert.assertNotEquals(oldDataFilesPath, newDataFilesPath);
+    Assert.assertNotEquals(oldDeleteFilesPath, newDeleteFilesPath);
+
+    optimizeCommit.commit(baseSnapshotId);
+    Assert.assertTrue(testKeyedTable.io().exists(newDataFilesPath.iterator().next()));
```
[the remark this answers is not in the document]
Comment (hzluting) [reply ams/ams-server/src/test/java/com/netease/arctic/ams/server/optimize/TestMajorOptimizeCommit.java:271]: Ok, I will add a test case to guarantee that deleting orphan files could work well.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java [hunk 3]
```diff
@@ -422,4 +425,31 @@ private static Set<ContentFile<?>> selectMajorOptimizeDeletedFiles(BaseOptimizeT
 
     return result;
   }
+
+  private static Set<String> getCommittedDataFilesFromSnapshotId(ArcticTable arcticTable, long snapshotId) {
```
[the remark this answers is not in the document]
Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java]: OK

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java (hunk 1 above)
Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java]: OK

**Review by zhoujinsong — COMMENTED** [review]
@hzluting  I left some comments.

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java [hunk 4]
```diff
@@ -422,4 +431,24 @@ private static Set<ContentFile<?>> selectMajorOptimizeDeletedFiles(BaseOptimizeT
...
+    for (Snapshot snapshot : SnapshotUtil.ancestorsBetween(currentSnapshotId, snapshotId, table::snapshot)) {
+      for (DataFile dataFile : snapshot.addedFiles()) {
+        committedFilePath.add(getUriPath(dataFile.path().toString()));
+      }
+    }
+
+    return committedFilePath;
+  }
+
+  private static String getUriPath(String path) {
```
[the remark this answers is not in the document]
Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/optimize/BaseOptimizeCommit.java:451]: OK

File: ams/ams-server/src/test/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanServiceTest.java [hunk 5]
```diff
@@ -18,17 +18,18 @@
 
 package com.netease.arctic.ams.server.service.impl;
 
+import com.netease.arctic.utils.FileUtil;
 import org.junit.Assert;
 import org.junit.Test;
 
 public class OrphanFilesCleanServiceTest {
   @Test
   public void testGetUriPath() {
```
Comment (wangtaohz) [inline ams/ams-server/src/test/java/com/netease/arctic/ams/server/service/impl/OrphanFilesCleanServiceTest.java:27]: This test case should move to `FileUtilTest`, and `OrphanFilesCleanServiceTest` can be removed
