### PR TITLE
[ARCTIC-1404][Core]Fix bug: Unable to synchronize newly added fields in non-primary table to Hive when use Spark

### LINKED ISSUE #1404: [Bug]: Unable to synchronize newly added fields in non-primary table to Hive when use Spark
### What happened?

When using Spark execute `alter table add column`. it is unable to synchronize newly added fields in non-primary table to Hive.

### Affects Versions

master

### What engines are you seeing the problem on?

Spark

### How to reproduce

1. create table test (
    id int,
    name string,
    day string) using arctic partitioned by(day);
2. alter table test add COLUMN os STRING COMMENT '1';
3. desc test.

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hellojinsilei**
## Why are the changes needed?

resolve #1404 
When using Spark execute alter table add column. it is unable to synchronize newly added fields in non-primary table to Hive.

## Brief change log

Change in `TracedTransaction.class`

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: hive/src/main/java/com/netease/arctic/hive/op/HiveSchemaUpdate.java [hunk 1]
```diff
@@ -35,32 +36,34 @@
...
-    syncSchemaToHive();
+    syncSchemaToHive(newSchema);
   }
 
-  private void syncSchemaToHive() {
+  private void syncSchemaToHive(Schema newSchema) {
     org.apache.hadoop.hive.metastore.api.Table tbl = HiveTableUtil.loadHmsTable(hiveClient, arcticTable.id());
     if (tbl == null) {
       throw new RuntimeException(String.format("there is no such hive table named %s", arcticTable.id().toString()));
     }
```
Comment (baiyangtx) [inline hive/src/main/java/com/netease/arctic/hive/op/HiveSchemaUpdate.java:63]: I think it better to check the condition before iceberg commit.

File: hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java [hunk 2]
```diff
@@ -127,7 +127,7 @@ private static boolean updateStructSchema(TableIdentifier tableIdentifier, Updat
           }
         }
       } else {
-        throw new RuntimeException("Exist columns with the same name: " + fields.get(0));
+        LOG.error("Exist columns with the same name: " + fields.get(0));
       }
```
Comment (baiyangtx) [inline hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:131]: I think it's a bad idea to compatible with exceptional cases.

**Review by baiyangtx — APPROVED** [review]
