### PR TITLE
[ARCTIC-462][AMS]Fix only rewrite DeleteFiles problem for support Hive

### LINKED ISSUE #462: [Bug][AMS]: Major Optimize isn't support hive
### What happened?

Now, Hive can't read data after optimize.
Because Major commit use rewrite that isn't support Hive

### Affects Versions

0.3.2

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hzluting**
## Why are the changes needed?
fix #462 
Full optimize will use RewriteFiles to delete DeleteFiles, but RewriteHiveFiles will overwrite DataFiles commit info before, will cause hive partition info incorrect.

## Brief change log

  - *when there  have no addDataFiles or deleteDataFiles, don't need to support hive*

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java [hunk 1]
```diff
@@ -99,6 +97,16 @@ public void commit() {
       this.partitionToCreate = getCreatePartition(this.partitionToDelete);
     }
 
+    // if no DataFiles to add or delete in Hive location, only commit to iceberg
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java:100]: I recommend add this if statement  before line 116 to avoid duplicate code at line 101-105 and line 110-114

**Review by zhoujinsong — CHANGES_REQUESTED** [review]
@hzluting  I left some comments. PTAL

File: hive/src/main/java/com/netease/arctic/hive/op/RewriteHiveFiles.java [hunk 2]
```diff
@@ -31,6 +32,18 @@ SnapshotUpdate<?> getSnapshotUpdateDelegate() {
     return delegate;
   }
 
+  @Override
+  public void commit() {
+    if (CollectionUtils.isEmpty(addFiles) && CollectionUtils.isEmpty(deleteFiles)) {
```
[the remark this answers is not in the document]
Comment (hzluting) [reply hive/src/main/java/com/netease/arctic/hive/op/RewriteHiveFiles.java:37]: yes，I will remove it

File: hive/src/main/java/com/netease/arctic/hive/op/OverwriteHiveFiles.java [hunk 3]
```diff
@@ -48,6 +50,8 @@ SnapshotUpdate<?> getSnapshotUpdateDelegate() {
 
   @Override
   public OverwriteFiles overwriteByRowFilter(Expression expr) {
+    Preconditions.checkArgument(!table.spec().isUnpartitioned() || expr == Expressions.alwaysTrue(),
+        "Unpartition support hive table don't support overwriteByRowFilter");
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/op/OverwriteHiveFiles.java:54]:
```suggestion
        "Unpartitioned hive table support alwaysTrue expression only");
```

File: hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java [hunk 4]
```diff
@@ -99,11 +98,20 @@ public void commit() {
...
+    boolean isNoHiveDataFiles = CollectionUtils.isEmpty(addFiles) && CollectionUtils.isEmpty(deleteFiles) &&
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java:102]: I recommend to change `isNoHiveDataFiles` to `noHiveDataFilesChanged`

**Review by zhoujinsong — APPROVED** [review]
LGTM.
