### PR TITLE
[ARCTIC-635]Skip cleaning maniftes files when commiting failed for hadoop table

### LINKED ISSUE #635: [Bug]: Flink Ingestion jobs will occasionally delete snapshot files causing Optimize and Flink Job to fail
### What happened?

When the Flink Ingestion job failsover several times, restarting the job will occasionally result in a java.io.FileNotFoundException: File does not exist exception for the snap-xxx.avro file.

### Affects Versions

0.3.x

### What engines are you seeing the problem on?

Flink

### How to reproduce

After starting a Flink job and writing some data normally, it frequently triggers Failover for a period of time causing the job to fail. Restart the task you just started.

### Relevant log output

```shell
java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at 
java.lang.reflect.Method.invoke(Method.java:498) at 
com.netease.arctic.flink.interceptor.KerberosInvocationHandler.lambda$invoke$0(KerberosInvocationHandler.java:58) at 
com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:301) at 
java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:360) at 
org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1734) at 
com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:299) at 
com.netease.arctic.io.ArcticHadoopFileIO.doAs(ArcticHadoopFileIO.java:177) at 
com.netease.arctic.flink.interceptor.KerberosInvocationHandler.invoke(KerberosInvocationHandler.java:55) at 
com.sun.proxy.$Proxy37.initializeState(Unknown Source) at 
org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:427) at 
org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$2(StreamTask.java:545) at 
org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50) at 
org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:535) at 
org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:575) at 
org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:758) at org.apache.flink.runtime.taskmanager.Task.run(Task.java:573) 
at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.reflect.InvocationTargetException at 
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at 
java.lang.reflect.Method.invoke(Method.java:498) at 
com.netease.arctic.flink.interceptor.KerberosInvocationHandler.lambda$invoke$0(KerberosInvocationHandler.java:58) at 
com.netease.arctic.table.TableMetaStore.lambda$doAs$0(TableMetaStore.java:301) at 
java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:360) at 
org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1734) at 
com.netease.arctic.table.TableMetaStore.doAs(TableMetaStore.java:299) at 
com.netease.arctic.io.ArcticHadoopFileIO.doAs(ArcticHadoopFileIO.java:177) at 
com.netease.arctic.flink.interceptor.KerberosInvocationHandler.invoke(KerberosInvocationHandler.java:55) at 
com.sun.proxy.$Proxy37.initializeState(Unknown Source) ... 21 more Caused by: 
com.netease.arctic.shaded.org.apache.iceberg.exceptions.NotFoundException: Failed to open input stream for file: 
hdfs://eadhadoop/user/da_luna/hive_db/da_luna.db/arctic_wow_outlog/change/metadata/snap-4720345255491225694-1-
2100685a-488a-496f-88b5-58206170c497.avro at 
com.netease.arctic.shaded.org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:177) at 
com.netease.arctic.shaded.org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:101) at 
com.netease.arctic.shaded.org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77) at 
com.netease.arctic.shaded.org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37) at 
com.netease.arctic.shaded.org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:320) at 
com.netease.arctic.shaded.org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:237) at 
com.netease.arctic.shaded.org.apache.iceberg.ManifestLists.read(ManifestLists.java:46) at 
com.netease.arctic.shaded.org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:137) at 
com.netease.arctic.shaded.org.apache.iceberg.BaseSnapshot.dataManifests(BaseSnapshot.java:159) at 
com.netease.arctic.shaded.org.apache.iceberg.MergingSnapshotProducer.apply(MergingSnapshotProducer.java:403) at 
com.netease.arctic.shaded.org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:164) at 
com.netease.arctic.shaded.org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:283) at 
com.netease.arctic.shaded.org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:405) at 
com.netease.arctic.shaded.org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214) at 
com.netease.arctic.shaded.org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198) at 
com.netease.arctic.shaded.org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190) at 
com.netease.arctic.shaded.org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:282) at 
com.netease.arctic.trace.TracedAppendFiles.commit(TracedAppendFiles.java:81) at 
com.netease.arctic.shaded.org.apache.iceberg.flink.sink.IcebergFilesCommitter.commitOperation(IcebergFilesCommitter.java:30
8) at 
com.netease.arctic.shaded.org.apache.iceberg.flink.sink.IcebergFilesCommitter.commitDeltaTxn(IcebergFilesCommitter.java:277) 
at 
com.netease.arctic.shaded.org.apache.iceberg.flink.sink.IcebergFilesCommitter.commitUpToCheckpoint(IcebergFilesCommitter.j
ava:219) at 
com.netease.arctic.shaded.org.apache.iceberg.flink.sink.IcebergFilesCommitter.initializeState(IcebergFilesCommitter.java:154) at 
org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:
112) at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:290) ... 34 
more Caused by: java.io.FileNotFoundException: File does not exist: 
/user/da_luna/hive_db/da_luna.db/arctic_wow_outlog/change/metadata/snap-4720345255491225694-1-2100685a-488a-496f-
88b5-58206170c497.avro at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86) at 
org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76) at 
org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:156) at 
org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2099) at 
org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:780) at 
org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtoc
olServerSideTranslatorPB.java:458) at 
org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:604) at 
org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:572) at 
org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:556) at 
org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093) at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1043) at 
org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:971) at java.base/javax.security.auth.Subject.doAs(Subject.java:423) at 
org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878) at 
org.apache.hadoop.ipc.Server$Handler.run(Server.java:2976) at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native 
Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at 
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at 
java.lang.reflect.Constructor.newInstance(Constructor.java:423) at 
org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106) at 
org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:73) at 
org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1237) at 
org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1222) at 
org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1210) at 
org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:306) at 
org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:272) at org.apache.hadoop.hdfs.DFSInputStream.<init>
(DFSInputStream.java:264) at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1535) at 
org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:304) at 
org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:299) at 
org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) at 
org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:312) at 
org.apache.hadoop.fs.FileSystem.open(FileSystem.java:768) at 
com.netease.arctic.shaded.org.apache.iceberg.hadoop.HadoopInputFile.newStream(HadoopInputFile.java:175) ... 57 more 
Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: 
/user/da_luna/hive_db/da_luna.db/arctic_wow_outlog/change/metadata/snap-4720345255491225694-1-2100685a-488a-496f-
88b5-58206170c497.avro at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86) at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76) at 
org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:156) at 
org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2099) at 
org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:780) at 
org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtoc
olServerSideTranslatorPB.java:458) at 
org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:604) at 
org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:572) at 
org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:556) at 
org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093) at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1043) at 
org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:971) at java.base/javax.security.auth.Subject.doAs(Subject.java:423) at 
org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878) at 
org.apache.hadoop.ipc.Server$Handler.run(Server.java:2976) at org.apache.hadoop.ipc.Client.call(Client.java:1476) at 
org.apache.hadoop.ipc.Client.call(Client.java:1413) at 
org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229) at 
com.sun.proxy.$Proxy27.getBlockLocations(Unknown Source) at 
org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslato
rPB.java:255) at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at 
java.lang.reflect.Method.invoke(Method.java:498) at 
org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191) at 
org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) at 
com.sun.proxy.$Proxy28.getBlockLocations(Unknown Source) at 
org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1235) ... 69 more


```

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by zhoujinsong**
## Why are the changes needed?

*Fix #635*

## Brief change log

  - *Throw CommitStateUnknownException when Hadoop table commit failed*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no)**
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

File: core/src/main/java/com/netease/arctic/op/ArcticHadoopTableOperations.java [hunk 1]
```diff
@@ -42,7 +43,16 @@ public TableMetadata refresh() {
   @Override
   public void commit(TableMetadata base, TableMetadata metadata) {
     arcticFileIO.doAs(() -> {
-      super.commit(base, metadata);
+      try {
+        super.commit(base, metadata);
+      } catch (RuntimeException e) {
```
Comment (zstraw) [inline core/src/main/java/com/netease/arctic/op/ArcticHadoopTableOperations.java:48]: we can distinguish the CommitFailedException in rename to avoid ignoring retry when commit conflict.

Comment (zhoujinsong) [reply core/src/main/java/com/netease/arctic/op/ArcticHadoopTableOperations.java]: SGTM.

**Review by zstraw — APPROVED** [review]
LGTM

**Review by wangtaohz — APPROVED** [review]
LGTM. I test it and catch exception here.
image
