### PR TITLE
[Bug]: Unexpected data in Operations section of table details

### LINKED ISSUE #1453: [Bug]: Unexpected data in Operations section of table details
### What happened?

image
As shown in the figure, without performing any operation on the table, it can be seen that these Properties are repeatedly submitted in the Operation page, with repeated SET and UNSET operations.

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

AMS

### How to reproduce

1.Configure the following parameters on the Catalog configuration page
image
2. Create a new Arctic table, enable self-optimizing, and write data through Flink

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hameizi**
## Why are the changes needed?
resolve #1453 

## Brief change log

When reporting properties, tracer needs to merge catalog properties.

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: core/src/main/java/com/netease/arctic/trace/AmsTableTracer.java [hunk 1]
```diff
@@ -175,8 +177,13 @@ public void commit() {
       update = true;
     }
     if (this.properties != null && Constants.INNER_TABLE_BASE.equals(innerTable)) {
-      commitMeta.setProperties(this.properties);
-      update = true;
+      try {
+        Map<String, String> catalogProperties = client.getCatalog(table.id().getCatalog()).getCatalogProperties();
+        commitMeta.setProperties(CatalogUtil.mergeCatalogPropertiesToTable(this.properties, catalogProperties));
```
Comment (Aireed) [inline core/src/main/java/com/netease/arctic/trace/AmsTableTracer.java:182]: mergeCatalogPropertiesToTable may throw NPE  for catalogProperties may be null .

**Review by Aireed — CHANGES_REQUESTED** [review]

File: core/src/main/java/com/netease/arctic/trace/AmsTableTracer.java (hunk 1 above)
Comment (hameizi) [reply core/src/main/java/com/netease/arctic/trace/AmsTableTracer.java]: fixed

**Review by Aireed — APPROVED** [review]
LGTM
