### PR TITLE
[ARCTIC-1686] Update status start time after optimizing status changed to pending

### LINKED ISSUE #1686: [Bug]: `Duration` is not updated after the table optimizing status change from `idle` to `pending`
### What happened?

The `Duration` is not updated after the table changed from `idle` to `pending`.
image

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

AMS

### How to reproduce

Without starting the optimizer, when keep inserting data into a table, the table's optimizing status will become `pending`, but the duration will not change.

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

fix #1686 

## Brief change log
  - update currentStatusStartTime after change to pending

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

File: ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java [hunk 1]
```diff
@@ -171,6 +171,7 @@ public void setPendingInput(OptimizingEvaluator.PendingInput pendingInput) {
       this.pendingInput = pendingInput;
       if (optimizingStatus == OptimizingStatus.IDLE) {
         this.currentChangeSnapshotId = System.currentTimeMillis();
+        this.currentStatusStartTime = System.currentTimeMillis();
```
Comment (zhoujinsong) [inline ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java:174]: If `currentStatusStartTime` and `optimizingStatus` always change together, would it be better to abstract a method to encapsulate their changes?

Comment (wangtaohz) [reply ams/server/src/main/java/com/netease/arctic/server/table/TableRuntime.java:174]: Yes, it is. I will extract a method to handle the change.

**Review by zhoujinsong — APPROVED** [review]
LGTM.
