### PR TITLE
[ARCTIC-981] Fix the Kerberos problem in the SortedPosDeleteWriter for the minor optimizing

### LINKED ISSUE #981: [Bug][Optimizer]:The optimizer can't output pos-delete files in minor optimizing because the user is incorrect
### What happened?

image
The optimizer can't output pos-delete files in minor optimizing because the user is incorrect.

### Affects Versions

0.3.0

### What engines are you seeing the problem on?

_No response_

### How to reproduce

1. Create an arctic keyed table with user A
2. Start the optimizer with user B
3. Write some data and some deleted data into the change store and make the optimizer work
4. The pos-delete files maybe can't be produced by the optimizer, or the owner of pos-delete files is user B

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hzluting**
## Why are the changes needed?
fix #981 

## Brief change log

  - *use table io to close in SortedPosDeleteWriter and BaseTaskWriter*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: core/src/main/java/com/netease/arctic/io/writer/SortedPosDeleteWriter.java [hunk 1]
```diff
@@ -114,7 +114,10 @@ public void delete(CharSequence path, long pos, T row) {
   }
 
   public List<DeleteFile> complete() throws IOException {
-    close();
+    io.doAs(() -> {
```
Comment (zhoujinsong) [inline core/src/main/java/com/netease/arctic/io/writer/SortedPosDeleteWriter.java:117]: I recommend wrapping the authentication logic around `SortedPosDeleteWriter#flushDeletes` because it will be called by other ways not only by `SortedPosDeleteWriter#complete`.

**Review by zhoujinsong — COMMENTED** [review]
As the iceberg parquet writer may create new file from file system when close, should other writers like `BaseTaskWriter`, `IcebergFanoutPosDeleteWriter` should also add authentication logic arroundding when closing.

Reference:https://github.com/apache/iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java#L117

File: core/src/main/java/com/netease/arctic/io/writer/SortedPosDeleteWriter.java (hunk 1 above)
Comment (hzluting) [reply core/src/main/java/com/netease/arctic/io/writer/SortedPosDeleteWriter.java]: > I recommend wrapping the authentication logic around `SortedPosDeleteWriter#flushDeletes` because it will be called by other ways not only by `SortedPosDeleteWriter#complete`.

OK， I think it will be better.

**Review by zhoujinsong — APPROVED** [review]
LGTM.
