### PR TITLE
[ARCTIC-873][CORE]Fix bug:insert overwrite will throw exception

### LINKED ISSUE #873: [Bug]: Spark select table will throw FileNotFoundException
### What happened?

This is an occasional bug：
Use spark SQL insert overwrite lots of partitions, then execute select table will throw FileNotFoundexception

image

### Affects Versions

0.3.2

### What engines are you seeing the problem on?

Core, Spark

### How to reproduce

Step1: Create an unkeyed table
Step2: Insert overwrite sink table select from the source table
Step3: Select from the sink table

notice: The source table needs to have multiple partitions

### Relevant log output

_No response_

### Anything else

Query the file in the hdfs where an error occurs. No file exists in the directory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hellojinsilei**
## Why are the changes needed?

fix #873 

## Brief change log

change Map<StructLike, Partition> type to StructLikeMap

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

File: hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java [hunk 1]
```diff
@@ -202,7 +204,7 @@ protected Map<StructLike, Partition> getDeletePartition() {
       this.deleteFiles.addAll(deleteFilesByExpr);
     }
 
-    Map<StructLike, Partition> deletePartitions = Maps.newHashMap();
+    Map<StructLike, Partition> deletePartitions = StructLikeMap.create(table.spec().partitionType());
```
Comment (baiyangtx) [inline hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java:207]: The var type declare must change to StructLikeMap<XX>

File: hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java [hunk 2]
```diff
@@ -321,8 +323,10 @@ private Map<StructLike, Partition> filterNewPartitionNonExists(
               "delete and re-create with same location");
         } else {
           // this partition is need to alter, rather than delete
+          StructLikeWrapper structLikeWrapper = StructLikeWrapper.forType(table.spec().schema().asStruct());
+          structLikeWrapper.set(entry.getKey());
```
Comment (baiyangtx) [inline hive/src/main/java/com/netease/arctic/hive/op/UpdateHiveFiles.java:327]: StruckLikeWrapper is not needed.   

partitionToDelete.remove(entry.getKey) is ok

**Review by baiyangtx — CHANGES_REQUESTED** [review]

**Review by baiyangtx — APPROVED** [review]

**Review by zhoujinsong — APPROVED** [review]
LGTM.
