### PR TITLE
[ARCTIC-1153][Optimize] Put task back into the queue if polling tasks failed

### LINKED ISSUE #1153: [Bug][Optimize]: Optimize task status is always pending
### What happened?

The optimizing task status is always pending after the poll task failed.
image

### Affects Versions

0.3.0

### What engines are you seeing the problem on?

AMS

### How to reproduce
1. AMS running on sysdb mysql
2. Then make AMS failing to connect to mysql
3. Start an optimizer to poll task from AMS
4. Task's status is still Pending, but can't be executed by optimizer, unless restart AMS.

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hzluting**
## Why are the changes needed?
fix #1153 

## Brief change log

  - *Put task back into the queue if polling tasks failed*

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java [hunk 1]
```diff
@@ -561,19 +561,22 @@ public OptimizeTask poll(JobId jobId, final String attemptId, long waitTime) {
...
+              task.setMaxExecuteTime();
+              tableTaskHistory = task.onExecuting(jobId, attemptId);
             } catch (Exception e) {
               task.clearFiles();
               LOG.error("{} failed to load files from sysdb, try put task back into queue", task.getTaskId(), e);
               if (!tasks.offer(task)) {
+                LOG.error("{} failed to put task back into queue", task.getTaskId());
                 task.onFailed(new ErrorMessage(System.currentTimeMillis(), "failed to put task back into queue"), 0);
               }
+              continue;
```
Comment (wangtaohz) [inline ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java:578]: We should sleep for like 1 second, before `continue` (poll from the tasks again).

Comment (hzluting) [reply ams/ams-server/src/main/java/com/netease/arctic/ams/server/service/impl/OptimizeQueueService.java:585]: OK

**Review by wangtaohz — APPROVED** [review]
LGTM
