### PR TITLE
[ARCTIC-1016] Moving files will fail if the target parent directory doesn't exist in HDFS

### LINKED ISSUE #1016: [Bug][AMS]: Moving files will fail if the target parent directory doesn't exist in HDFS
### What happened?

For the unKeyed MIXED_HIVE table with partition, we will move the result files to the hive partition location to support the hive. The rename method will return false and doesn't throw the exception in HDFS when the target parent directory doesn't exist, but we don't handle it according to the return value.
So, the major optimizing commit will commit the file that isn't moved. The "File not found" exception will throw when we read or optimize this table.

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

_No response_

### How to reproduce

1. create an unKeyed MIXED_HIVE table with partition
2. trigger a major optimizing for this table and optimize the partition that doesn't exist in the hive
3. read this table will throw the "File not found" exception

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by shendanfengg**
## Why are the changes needed?

Fix #1016 

## Brief change log

*Exception thrown when FileSystem returns false.
*If the new path does not exist during Support Hive Commit,  and then create it.
*Fix some simple grammar errors.

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)

### CODE REVIEW

**Comment by hzluting** [comment]
cc @zhoujinsong

File: core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java [hunk 1]
```diff
@@ -165,9 +172,14 @@ public boolean rename(String src, String dts) {
...
+              " and file system return false, need to check the hdfs path");
+        } else {
+          return true;
+        }
       } catch (IOException e) {
-        throw new UncheckedIOException("Failed to rename: from " + src + " to " + dts, e);
+        throw new UncheckedIOException("Fail to rename: from " + src + " to " + dts, e);
       }
     });
   }
```
Comment (wangtaohz) [inline core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java:185]: If we choose to throw an exception when fail to rename, this method should return `void` instead of return `boolean`.

File: hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java [hunk 2]
```diff
@@ -73,7 +73,7 @@ private synchronized void init() {
   @Override
   public <R> R run(Action<R, HMSClient, TException> action) throws TException, InterruptedException {
     try {
-      return tableMetaStore.doAs(() -> clientPool().run(action));
+      return tableMetaStore.doAs(() -> clientPool().run(action, true));
```
Comment (wangtaohz) [inline hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java:76]: What problem is this going to fix? Is there another PR to fix this?

**Review by wangtaohz — COMMENTED** [review]
@shendanfengg Thanks for your work.

I left some comment, please take a look.

File: hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java (hunk 2 above)
Comment (shendanfengg) [reply hive/src/main/java/com/netease/arctic/hive/CachedHiveClientPool.java:76]: I have also committed this change in another pr and I will delete it in this pr.

**Review by wangtaohz — APPROVED** [review]

File: core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java [hunk 3]
```diff
@@ -84,6 +88,9 @@ public boolean deleteFileWithResult(String path, boolean recursive) {
       } catch (IOException e) {
         result = false;
       }
+      if (result == false) {
```
Comment (zhoujinsong) [inline core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java:91]:
```suggestion
      if (!result ) {
```

File: core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java [hunk 4]
```diff
@@ -159,16 +166,20 @@ public boolean isEmptyDirectory(String location) {
...
-  public boolean rename(String src, String dts) {
-    return tableMetaStore.doAs(() -> {
+  public void rename(String src, String dts) {
+    tableMetaStore.doAs(() -> {
       Path srcPath = new Path(src);
       Path dtsPath = new Path(dts);
       FileSystem fs = getFs(srcPath);
       try {
-        return fs.rename(srcPath, dtsPath);
+        if (fs.rename(srcPath, dtsPath) == false) {
```
Comment (zhoujinsong) [inline core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java:175]:
```suggestion
        if (!fs.rename(srcPath, dtsPath)) {
```

File: core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java [hunk 5]
```diff
@@ -185,21 +196,25 @@ public boolean exists(String path) {
...
   @Override
-  public boolean mkdirs(String path) {
-    return tableMetaStore.doAs(() -> {
+  public void mkdirs(String path) {
+    tableMetaStore.doAs(() -> {
       Path filePath = new Path(path);
       FileSystem fs = getFs(filePath);
       try {
-        return fs.mkdirs(filePath);
+        if (fs.mkdirs(filePath) == false) {
```
Comment (zhoujinsong) [inline core/src/main/java/com/netease/arctic/io/ArcticHadoopFileIO.java:210]:
```suggestion
        if (!fs.mkdirs(filePath)) {
```

**Review by zhoujinsong — COMMENTED** [review]
I left some suggestion, please task a look.

**Comment by wangtaohz** [comment]
I have cherry-picked it to 0.3.x
