### PR TITLE
[ARCTIC-1263] hive data sync to arctic error

### LINKED ISSUE #1263: [Bug]: hive data sync to arctic error
### What happened?

1. Synchronization of hive data to arctic occurs when hive data has not changed
2. Multiple triggers for hive sync to arctic at the same time may cause duplicate commits

### Affects Versions

0.4.0

### What engines are you seeing the problem on?

Core

### How to reproduce

Changing the arctic table's transient-time property, but not changing hive's transient_lastDdlTime, will trigger synchronization

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hameizi**
## Why are the changes needed?
resolve #1263 

## Brief change log

Sync hive to arctic only if hive partition location and arctic partition location are the same and transient_lastDdlTime is different

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java [hunk 1]
```diff
@@ -214,8 +214,16 @@ private static boolean partitionHasModified(UnkeyedTable arcticTable, Partition
...
     // compare hive partition parameter transient_lastDdlTime with arctic partition properties to
     // find out if the partition is changed.
+    String hiveLocation = hivePartition.getSd().getLocation();
+    String arcticPartitionLocation = arcticTable.partitionProperty().containsKey(partitionData) ?
+        arcticTable.partitionProperty().get(partitionData)
+            .get(HiveTableProperties.PARTITION_PROPERTIES_KEY_HIVE_LOCATION) : null;
+    if (arcticPartitionLocation != null && !arcticPartitionLocation.equals(hiveLocation)) {
+      return false;
+    }
     if (arcticTransientTime == null || !arcticTransientTime.equals(hiveTransientTime)) {
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:227]: Otherwise, we should move comment lines 218-219 here.

File: hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java [hunk 2]
```diff
@@ -230,6 +238,13 @@ private static boolean tableHasModified(UnkeyedTable arcticTable, Table table) {
       arcticTransientTime = structLikeMap.get(TablePropertyUtil.EMPTY_STRUCT)
           .get(HiveTableProperties.PARTITION_PROPERTIES_KEY_TRANSIENT_TIME);
     }
+    String hiveLocation = table.getSd().getLocation();
+    String arcticPartitionLocation = arcticTable.partitionProperty().containsKey(TablePropertyUtil.EMPTY_STRUCT) ?
+        arcticTable.partitionProperty().get(TablePropertyUtil.EMPTY_STRUCT)
+            .get(HiveTableProperties.PARTITION_PROPERTIES_KEY_HIVE_LOCATION) : null;
+    if (arcticPartitionLocation != null && !arcticPartitionLocation.equals(hiveLocation)) {
```
Comment (zhoujinsong) [inline hive/src/main/java/com/netease/arctic/hive/utils/HiveMetaSynchronizer.java:245]: Add some comments here too.

**Review by zhoujinsong — APPROVED** [review]
