### PR TITLE
[ARCTIC-1047][Core] Fix the the logic of estimating size in the SimpleSpillableMap

### LINKED ISSUE #1047: [Bug][Core]: The estimate of memory size is incorrect in the SimpleSpillableMap
### What happened?

When I tested the performance of the spill map, I found the performance of the memory map in the SimpleSpillableMap significantly worse than the performance of the SimpleMemoryMap.
I found the estimate of memory size is incorrect in the SimpleSpillableMap because the key is the StructLikeWrapper which contains extra content(such as Comparator). When we estimate the key's size of the memory map in memory, we should only consider the record's size in the StructLikeWrapper rather than its all size in the memory map because some content in the StructLikeWrapper references the same instance.

### Affects Versions

0.4.x

### What engines are you seeing the problem on?

Core

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hzluting**
## Why are the changes needed?
fix #1047

## Brief change log

  - *fix the logic of estimating size in the SimpleSpillableMap*
  - *unified the units in optimizer group config*

## How was this patch tested?
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

### CODE REVIEW

File: core/src/main/java/com/netease/arctic/utils/map/SizeEstimator.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.netease.arctic.utils.map;
+
+import org.openjdk.jol.info.GraphLayout;
```
Comment (wangtaohz) [inline core/src/main/java/com/netease/arctic/utils/map/SizeEstimator.java:21]: useless import

File: core/src/main/java/com/netease/arctic/utils/map/SimpleSpillableMap.java [hunk 2]
```diff
@@ -32,32 +31,44 @@
   private static final int RECORDS_TO_SKIP_FOR_ESTIMATING = 200;
   private final long maxInMemorySizeInBytes;
   private final String backendBaseDir;
+  // Size Estimator for key type
+  private final SizeEstimator<K> keySizeEstimator;
+  // Size Estimator for key types
+  private final SizeEstimator<T> valueSizeEstimator;
   private Map<K, T> memoryMap;
   private Optional<SimpleSpilledMap<K, T>> diskBasedMap = Optional.empty();
   private Long currentInMemoryMapSize;
```
Comment (wangtaohz) [inline core/src/main/java/com/netease/arctic/utils/map/SimpleSpillableMap.java:40]: `long currentInMemoryMapSize` may be better, since the `null` value is not used.

File: core/src/main/java/com/netease/arctic/utils/map/StructLikeWrapperSizeEstimator.java [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+import com.netease.arctic.iceberg.optimize.StructLikeWrapper;
+import com.netease.arctic.utils.ObjectSizeCalculator;
+
+/**
+ * Size Estimator for StructLikeWrapper record payload.
+ */
+public class StructLikeWrapperSizeEstimator implements SizeEstimator<StructLikeWrapper> {
+  @Override
+  public long sizeEstimate(StructLikeWrapper structLikeWrapper) {
+    return ObjectSizeCalculator.getObjectSize(structLikeWrapper.get());
```
Comment (wangtaohz) [inline core/src/main/java/com/netease/arctic/utils/map/StructLikeWrapperSizeEstimator.java:30]: If `structLikeWrapper == null`, it will incur NPE.

**Review by wangtaohz — COMMENTED** [review]
@hzluting Thanks for your contribution. I left some comments.

File: core/src/main/java/com/netease/arctic/utils/map/SizeEstimator.java (hunk 1 above)
Comment (hzluting) [reply core/src/main/java/com/netease/arctic/utils/map/SizeEstimator.java:21]: OK

File: core/src/main/java/com/netease/arctic/utils/map/SimpleSpillableMap.java (hunk 2 above)
Comment (hzluting) [reply core/src/main/java/com/netease/arctic/utils/map/SimpleSpillableMap.java:40]: Yes

File: core/src/main/java/com/netease/arctic/utils/map/StructLikeWrapperSizeEstimator.java (hunk 3 above)
Comment (hzluting) [reply core/src/main/java/com/netease/arctic/utils/map/StructLikeWrapperSizeEstimator.java:34]: OK

**Comment by wangtaohz** [comment]
LGTM

**Review by wangtaohz — APPROVED** [review]

**Review by zhoujinsong — APPROVED** [review]
The codes look good to me.
But I am wondering the spillablemap performance now.

File: core/src/main/java/com/netease/arctic/utils/map/StructLikeWrapperSizeEstimator.java [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+ * Size Estimator for StructLikeWrapper record payload.
+ */
+public class StructLikeWrapperSizeEstimator implements SizeEstimator<StructLikeWrapper> {
+  @Override
+  public long sizeEstimate(StructLikeWrapper structLikeWrapper) {
+    if (structLikeWrapper == null) {
+      return 0;
+    }
+
+    return ObjectSizeCalculator.getObjectSize(structLikeWrapper.get());
```
Comment (shidayang) [inline core/src/main/java/com/netease/arctic/utils/map/StructLikeWrapperSizeEstimator.java:34]: The object size is also incorrect, because StructLike is an interface. You only can calculate object size implementation

**Review by shidayang — CHANGES_REQUESTED** [review]

File: core/src/main/java/com/netease/arctic/utils/map/StructLikeWrapperSizeEstimator.java (hunk 4 above)
Comment (zhoujinsong) [reply core/src/main/java/com/netease/arctic/utils/map/StructLikeWrapperSizeEstimator.java:34]: StructLike had multiple implementations, should we implement different calculation process for different situation?

Comment (hzluting) [reply core/src/main/java/com/netease/arctic/utils/map/StructLikeWrapperSizeEstimator.java:34]: I find the key Serializer in the spill map uses the StructLikeCopy to serialize. The key in the StructLikeBaseMap also can use StructLikeCopy. And the size of the StructLikeCopy instance is affirmatory.

**Review by shidayang — APPROVED** [review]
